import { useEffect, useMemo, useRef, useState } from "react";
import clsx from "clsx";
import { DirectDepositSheet } from "../../components/paycheck/DirectDepositSheet";
import { LogPaycheckSheet } from "../../components/paycheck/LogPaycheckSheet";
import { TaxSetupSheet } from "../../components/paycheck/TaxSetupSheet";
import { formatUsd } from "../../lib/format";
import { useSalaryData } from "../../lib/salaryData";
import {
  PAY_FREQUENCY_LABELS,
  PAY_TYPE_LABELS,
  applyInferredPayRatesToConfig,
  canDetectMissingPaychecks,
  inferPayRatesFromLogs,
  isTaxSetupIncomplete,
  formatIsoDate,
  formatPercent,
  logsForYear,
  missingPaydaysForYear,
  parseIsoDate,
  projectFederalTaxReturn,
  summarizeYtd,
  type DirectDeposit,
  type PayFrequency,
  type PayRateChange,
  type PayType,
  type FederalTaxReturnProjection,
  type PaycheckLogEntry,
  type TaxOverrides,
  type YtdBreakdownLine,
} from "../../lib/salary";
import { FILING_STATUS_LABELS } from "../../lib/tax";

type PaycheckView = "summary" | "whatif";
type SummaryStatsView = "ytd" | "annual";

const VIEWS: { id: PaycheckView; label: string }[] = [
  { id: "summary", label: "Summary" },
  { id: "whatif", label: "Model" },
];

export function PaycheckTab() {
  const salary = useSalaryData();
  const [view, setView] = useState<PaycheckView>("summary");
  const [year, setYear] = useState(new Date().getFullYear());
  const [showLog, setShowLog] = useState(false);
  const [editingLog, setEditingLog] = useState<PaycheckLogEntry | null>(null);
  const [logPayDateHint, setLogPayDateHint] = useState<number | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [showTaxSetup, setShowTaxSetup] = useState(false);
  const [projectOvertimeForward, setProjectOvertimeForward] = useState(true);
  const [generatingLogs, setGeneratingLogs] = useState(false);
  const taxSetupIncomplete = isTaxSetupIncomplete(salary.config);

  const ytd = useMemo(
    () =>
      summarizeYtd(
        salary.config,
        salary.calculation,
        salary.annualProjection,
        year,
        Date.now(),
        { projectOvertimeForward },
      ),
    [
      salary.config,
      salary.calculation,
      salary.annualProjection,
      year,
      projectOvertimeForward,
    ],
  );

  const yearLogs = useMemo(
    () => logsForYear(salary.config, year),
    [salary.config, year],
  );

  const missingPaydays = useMemo(
    () => missingPaydaysForYear(salary.config, year),
    [salary.config, year],
  );

  const onRefresh = async () => {
    if (refreshing) return;
    setRefreshing(true);
    try {
      await salary.reload();
    } finally {
      setRefreshing(false);
    }
  };

  const openLog = (entry?: PaycheckLogEntry, payDateHint?: number) => {
    setEditingLog(entry ?? null);
    setLogPayDateHint(entry ? null : (payDateHint ?? null));
    setShowLog(true);
  };

  const onGenerateMissingLogs = async () => {
    if (generatingLogs || missingPaydays.length === 0) return;
    setGeneratingLogs(true);
    try {
      await salary.generateMissingPaycheckLogs(year);
    } catch {
      /* error shown via salary.error / sync overlay */
    } finally {
      setGeneratingLogs(false);
    }
  };

  const onLogSave = async (entry: PaycheckLogEntry) => {
    const manualEntry = { ...entry, autoGenerated: undefined };
    try {
      if (editingLog?.id) await salary.updatePaycheckLog(manualEntry);
      else await salary.addPaycheckLog(manualEntry);
      setEditingLog(null);
      setLogPayDateHint(null);
    } catch {
      /* error shown via salary.error / sync overlay */
    }
  };

  return (
    <div className="space-y-5">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h1 className="page-title">Paycheck</h1>
          <p className="text-sm text-muted mt-1">
            Track actual paychecks on Summary. Use Model for raises, bonuses,
            and other scenarios.
          </p>
        </div>
        <div className="flex gap-2 shrink-0">
          <button
            type="button"
            className="btn-ghost text-sm"
            onClick={() => void onRefresh()}
            disabled={refreshing}
          >
            {refreshing ? "Syncing…" : "Sync"}
          </button>
        </div>
      </div>

      <div className="flex items-stretch gap-2">
        <div className="flex-1 min-w-0">
          <SegmentedBar
            options={VIEWS}
            value={view}
            onChange={setView}
            ariaLabel="Paycheck view"
          />
        </div>
        <button
          type="button"
          onClick={() => setShowTaxSetup(true)}
          className="relative shrink-0 flex items-center px-3 py-2 rounded-lg border-2 border-primary bg-surfaceVariant/60 text-xs sm:text-sm font-semibold text-primary hover:bg-primaryContainer/40 transition-colors"
          title={
            taxSetupIncomplete
              ? "Set your tax info for accurate calculations"
              : `Tax — ${FILING_STATUS_LABELS[salary.config.filingStatus]}`
          }
          aria-label={
            taxSetupIncomplete
              ? "Tax setup incomplete"
              : `Tax — ${FILING_STATUS_LABELS[salary.config.filingStatus]}`
          }
        >
          Tax
          {taxSetupIncomplete ? (
            <span
              className="absolute top-1.5 right-1.5 w-2 h-2 rounded-full bg-error"
              aria-hidden
            />
          ) : null}
        </button>
      </div>

      {salary.loading ? (
        <p className="text-muted text-sm">Loading paycheck data…</p>
      ) : null}

      {salary.error ? (
        <div className="card-quiet p-4 text-sm text-error" role="alert">
          {salary.error}
        </div>
      ) : null}

      {!salary.loading ? (
        <>
          {view === "summary" ? (
            <SummaryView
              year={year}
              onYearChange={setYear}
              ytd={ytd}
              logs={yearLogs}
              missingPaydays={missingPaydays}
              config={salary.config}
              calc={salary.calculation}
              setConfig={salary.setConfig}
              canDetectMissing={canDetectMissingPaychecks(salary.config, year)}
              onLogPaycheck={() => openLog()}
              onLogMissingPaycheck={(payDate) => openLog(undefined, payDate)}
              onEditLog={(e) => openLog(e)}
              onDeleteLog={(id) => void salary.removePaycheckLog(id)}
              onGenerateMissingLogs={() => void onGenerateMissingLogs()}
              generatingLogs={generatingLogs}
              projectOvertimeForward={projectOvertimeForward}
              onProjectOvertimeForwardChange={setProjectOvertimeForward}
            />
          ) : null}
          {view === "whatif" ? (
            <WhatIfView
              config={salary.config}
              calc={salary.calculation}
              setConfig={salary.setConfig}
              annualOvertimeHours={salary.annualOvertimeHours}
              projection={salary.annualProjection}
              baseline={salary.annualBaseline}
              onOvertimeChange={salary.setAnnualOvertimeHours}
              whatIfDeposits={salary.whatIfDirectDeposits ?? salary.config.directDeposits}
              whatIfDepositAllocations={salary.whatIfDepositAllocations}
              whatIfDepositsCustomized={salary.whatIfDepositsCustomized}
              onWhatIfDepositsChange={salary.setWhatIfDirectDeposits}
              onResetWhatIfDeposits={salary.resetWhatIfDirectDeposits}
              onLogPaycheck={() => openLog()}
            />
          ) : null}
        </>
      ) : null}

      <TaxSetupSheet
        open={showTaxSetup}
        onClose={() => setShowTaxSetup(false)}
        config={salary.config}
        setConfig={salary.setConfig}
      />

      <LogPaycheckSheet
        key={editingLog?.id ?? logPayDateHint ?? "new-log"}
        open={showLog}
        onClose={() => {
          setShowLog(false);
          setEditingLog(null);
          setLogPayDateHint(null);
        }}
        config={salary.config}
        calculation={salary.calculation}
        editing={editingLog}
        payDateHint={logPayDateHint}
        onSave={onLogSave}
      />
    </div>
  );
}

function SummaryView({
  year,
  onYearChange,
  ytd,
  logs,
  missingPaydays,
  canDetectMissing,
  config,
  calc,
  setConfig,
  onLogPaycheck,
  onLogMissingPaycheck,
  onEditLog,
  onDeleteLog,
  onGenerateMissingLogs,
  generatingLogs,
  projectOvertimeForward,
  onProjectOvertimeForwardChange,
}: {
  year: number;
  onYearChange: (y: number) => void;
  ytd: ReturnType<typeof summarizeYtd>;
  logs: PaycheckLogEntry[];
  missingPaydays: number[];
  canDetectMissing: boolean;
  config: ReturnType<typeof useSalaryData>["config"];
  calc: ReturnType<typeof useSalaryData>["calculation"];
  setConfig: ReturnType<typeof useSalaryData>["setConfig"];
  onLogPaycheck: () => void;
  onLogMissingPaycheck: (payDate: number) => void;
  onEditLog: (e: PaycheckLogEntry) => void;
  onDeleteLog: (id: string) => void;
  onGenerateMissingLogs: () => void;
  generatingLogs: boolean;
  projectOvertimeForward: boolean;
  onProjectOvertimeForwardChange: (value: boolean) => void;
}) {
  const currentYear = new Date().getFullYear();
  const annual = ytd.annualExtrapolation;
  const [statsView, setStatsView] = useState<SummaryStatsView>("ytd");
  const inferredPayRates = useMemo(
    () => inferPayRatesFromLogs(config, year),
    [config, year],
  );
  const federalReturn = useMemo(
    () => projectFederalTaxReturn(config, annual),
    [config, annual],
  );

  const logsSig = logs
    .map((l) => `${l.id}:${l.payDate}:${l.grossPay}`)
    .join("|");
  useEffect(() => {
    setConfig((current) => {
      const next = applyInferredPayRatesToConfig(current, year);
      const historySame =
        JSON.stringify(next.payRateHistory ?? []) ===
        JSON.stringify(current.payRateHistory ?? []);
      const baseSame =
        next.hourlyRate === current.hourlyRate &&
        next.annualSalary === current.annualSalary &&
        next.standardHoursPerPeriod === current.standardHoursPerPeriod &&
        next.payType === current.payType;
      if (historySame && baseSame) return current;
      return next;
    });
  }, [year, logsSig, setConfig]);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <button
            type="button"
            className="btn-ghost text-sm px-3"
            onClick={() => onYearChange(year - 1)}
            aria-label="Previous year"
          >
            ←
          </button>
          <span className="font-serif text-lg font-semibold text-heading">
            {year}
          </span>
          <button
            type="button"
            className="btn-ghost text-sm px-3"
            onClick={() => onYearChange(year + 1)}
            disabled={year >= currentYear}
            aria-label="Next year"
          >
            →
          </button>
        </div>
        <button type="button" className="btn-primary text-sm" onClick={onLogPaycheck}>
          Log paycheck
        </button>
      </div>

      <section className="card p-5 bg-dollar-gradient">
        <div className="flex items-center justify-between gap-2">
          <p className="text-xs tracking-wider text-muted font-medium">
            Year-To-Date Net
          </p>
          <span
            className={clsx(
              "text-xs px-2 py-0.5 rounded-pill font-medium",
              ytd.source === "logged" ? "badge-success" : "badge-autopay",
            )}
          >
            {ytd.source === "logged" ? "Logged" : "Estimated"}
          </span>
        </div>
        <p className="money text-3xl mt-1">{formatUsd(ytd.netPay)}</p>
        <div className="mt-3 h-2 rounded-full bg-surfaceVariant overflow-hidden">
          <div
            className="h-full bg-primary rounded-full transition-all"
            style={{
              width: `${Math.min(100, ytd.progressPercent)}%`,
            }}
          />
        </div>
        <p className="text-xs text-muted mt-2">
          {ytd.progressPercent.toFixed(0)}% of projected annual net (
          {formatUsd(ytd.annualNetTarget)})
        </p>
        <SegmentedBar
          className="mt-4"
          options={[
            { id: "ytd", label: "Year To Date" },
            { id: "annual", label: "Projected Annual" },
          ]}
          value={statsView}
          onChange={setStatsView}
          ariaLabel="Summary statistics view"
        />
      </section>

      {statsView === "ytd" ? (
        <>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <Stat label="Gross YTD" value={formatUsd(ytd.grossPay)} />
            <Stat label="Taxes YTD" value={formatUsd(ytd.totalTaxes)} />
            <Stat
              label="Deductions YTD"
              value={formatUsd(ytd.totalDeductions)}
            />
            <Stat label="OT hours YTD" value={ytd.overtimeHours.toFixed(1)} />
          </div>

          <BreakdownCard
            title="Earnings"
            lines={ytd.earnings}
            total={ytd.grossPay}
          />
          <BreakdownCard
            title="Taxes"
            lines={ytd.taxes}
            total={ytd.totalTaxes}
            negative
            footer={`Effective tax rate ${
              ytd.grossPay > 0
                ? ((ytd.totalTaxes / ytd.grossPay) * 100).toFixed(1)
                : "0.0"
            }%`}
          />
          {ytd.preTaxDeductions.length > 0 ? (
            <BreakdownCard
              title="Pre-Tax Deductions"
              lines={ytd.preTaxDeductions}
              total={ytd.totalPreTaxDeductions}
              negative
            />
          ) : null}
          {ytd.postTaxDeductions.length > 0 ? (
            <BreakdownCard
              title="Post-Tax Deductions"
              lines={ytd.postTaxDeductions}
              total={ytd.totalPostTaxDeductions}
              negative
            />
          ) : null}
          {ytd.employerContributions.length > 0 ? (
            <BreakdownCard
              title="Employer Contributions"
              lines={ytd.employerContributions}
              total={ytd.employerContributions.reduce((s, l) => s + l.amount, 0)}
            />
          ) : null}
        </>
      ) : (
        <>
          <div className="flex items-center justify-end">
            <span
              className={clsx(
                "text-xs px-2 py-0.5 rounded-pill font-medium",
                annual.source === "logged" ? "badge-success" : "badge-autopay",
              )}
            >
              {annual.source === "logged"
                ? "From your paychecks"
                : "Estimated"}
            </span>
          </div>

          <p className="text-sm text-muted -mt-2">
            {annual.source === "logged"
              ? `YTD actuals from ${annual.basedOnPaychecks} logged paycheck${
                  annual.basedOnPaychecks === 1 ? "" : "s"
                }, plus latest pay rate × ${annual.remainingPaychecksProjected} remaining pay period${
                  annual.remainingPaychecksProjected === 1 ? "" : "s"
                }.`
              : "Log paychecks to project from actual stubs, or use Model settings until then."}
          </p>

          {annual.source === "logged" ? (
            <label className="flex items-center justify-between gap-3 card-quiet p-3 text-sm cursor-pointer">
              <span className="text-muted">
                Project average OT forward
                {annual.averageOvertimeHoursPerPaycheck > 0 ? (
                  <>
                    {" "}
                    (
                    <span className="text-body font-medium">
                      {annual.averageOvertimeHoursPerPaycheck.toFixed(1)}
                    </span>{" "}
                    hrs/paycheck so far)
                  </>
                ) : null}
              </span>
              <input
                type="checkbox"
                className="h-4 w-4 accent-primary"
                checked={projectOvertimeForward}
                onChange={(e) =>
                  onProjectOvertimeForwardChange(e.target.checked)
                }
              />
            </label>
          ) : null}

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <Stat
              label="Projected net"
              value={formatUsd(annual.annualNetPay)}
            />
            <Stat
              label="Projected gross"
              value={formatUsd(annual.annualGrossPay)}
            />
            <Stat
              label="Projected taxes"
              value={formatUsd(annual.annualTotalTaxes)}
            />
            <Stat
              label="Per paycheck"
              value={formatUsd(annual.perPaycheckNet)}
            />
          </div>

          <section className="card-quiet p-4 text-sm text-muted">
            <p>
              <span className="text-body font-medium">
                {annual.scheduledPaychecksInYear}
              </span>{" "}
              pay periods this year ·{" "}
              <span className="text-body font-medium">
                {annual.overtimeHours.toFixed(1)}
              </span>{" "}
              projected OT hours
              {annual.source === "logged" && !annual.projectOvertimeForward
                ? " (logged only)"
                : ""}{" "}
              ·{" "}
              <span className="text-body font-medium">
                {formatUsd(annual.annualTotalDeductions)}
              </span>{" "}
              projected deductions
            </p>
          </section>

          <FederalTaxReturnSection
            projection={federalReturn}
            filingStatus={config.filingStatus}
          />

          {annual.earnings.length > 0 ? (
            <BreakdownCard
              title="Earnings"
              lines={annual.earnings}
              total={annual.annualGrossPay}
            />
          ) : null}
          {annual.taxes.length > 0 ? (
            <BreakdownCard
              title="Taxes"
              lines={annual.taxes}
              total={annual.annualTotalTaxes}
              negative
              footer={`Effective rate ${(annual.effectiveTaxRate * 100).toFixed(1)}%`}
            />
          ) : null}
          {annual.preTaxDeductions.length > 0 ? (
            <BreakdownCard
              title="Pre-Tax Deductions"
              lines={annual.preTaxDeductions}
              total={annual.annualPreTaxDeductions}
              negative
            />
          ) : null}
          {annual.postTaxDeductions.length > 0 ? (
            <BreakdownCard
              title="Post-Tax Deductions"
              lines={annual.postTaxDeductions}
              total={annual.annualPostTaxDeductions}
              negative
            />
          ) : null}
          {annual.employerContributions.length > 0 ? (
            <BreakdownCard
              title="Employer Contributions"
              lines={annual.employerContributions}
              total={annual.employerContributions.reduce(
                (s, l) => s + l.amount,
                0,
              )}
            />
          ) : null}
        </>
      )}

      {statsView === "ytd" ? (
        <>
      <section className="card p-5">
        <h2 className="section-title">Paycheck Schedule</h2>
        <div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label className="label" htmlFor="summary-pay-freq">
              Pay frequency
            </label>
            <select
              id="summary-pay-freq"
              className="input"
              value={config.payFrequency}
              onChange={(e) =>
                setConfig((c) => ({
                  ...c,
                  payFrequency: e.target.value as PayFrequency,
                }))
              }
            >
              {(Object.keys(PAY_FREQUENCY_LABELS) as PayFrequency[]).map(
                (f) => (
                  <option key={f} value={f}>
                    {PAY_FREQUENCY_LABELS[f]}
                  </option>
                ),
              )}
            </select>
          </div>
          <div>
            <label className="label" htmlFor="summary-first-payday">
              First payday of year
            </label>
            <input
              id="summary-first-payday"
              className="input"
              type="date"
              value={
                config.firstPaydayOfYearMillis
                  ? formatIsoDate(config.firstPaydayOfYearMillis)
                  : ""
              }
              onChange={(e) =>
                setConfig((c) => ({
                  ...c,
                  firstPaydayOfYearMillis: parseIsoDate(e.target.value),
                }))
              }
            />
          </div>
        </div>
        <p className="text-xs text-muted mt-2">
          {config.payFrequency === "WEEKLY" ||
          config.payFrequency === "BIWEEKLY"
            ? "Pay frequency and first payday are required for weekly and biweekly schedules. Logged paychecks on matching dates are recognized automatically."
            : "Pay frequency drives YTD counting and Model calculations. First payday improves monthly estimates."}
        </p>
      </section>

      <section className="card p-5">
        <div className="flex items-start justify-between gap-3">
          <h2 className="section-title">Paycheck Log</h2>
          <button
            type="button"
            className="btn-ghost text-xs sm:text-sm shrink-0"
            onClick={onGenerateMissingLogs}
            disabled={
              generatingLogs ||
              missingPaydays.length === 0 ||
              !canDetectMissing ||
              calc.grossPay <= 0
            }
            title={
              !canDetectMissing
                ? "Set pay frequency and first payday to detect missing checks"
                : calc.grossPay <= 0
                  ? "Set your pay rate before generating estimates"
                  : missingPaydays.length === 0
                    ? "No missing paychecks for this year"
                    : `Add ${missingPaydays.length} estimated paycheck${missingPaydays.length === 1 ? "" : "s"} from calculator`
            }
          >
            {generatingLogs
              ? "Generating…"
              : `Generate missing${missingPaydays.length > 0 ? ` (${missingPaydays.length})` : ""}`}
          </button>
        </div>
        <p className="text-sm text-muted mt-1">
          <span className="text-body font-medium">{ytd.scheduledPaychecksYtd}</span>{" "}
          paycheck{ytd.scheduledPaychecksYtd === 1 ? "" : "s"} received ·{" "}
          <span className="text-body font-medium">{ytd.scheduledPaychecksInYear}</span>{" "}
          expected this year
          {ytd.remainingPaychecks > 0 ? (
            <>
              {" "}
              ·{" "}
              <span className="text-body font-medium">{ytd.remainingPaychecks}</span>{" "}
              remaining
            </>
          ) : null}
        </p>
        {logs.length === 0 && missingPaydays.length === 0 ? (
          <p className="text-sm text-muted mt-1">
            {canDetectMissing
              ? "No paychecks logged for this year yet. Log your first paycheck to track actual earnings."
              : "No paychecks logged for this year yet. Set your first payday of the year above to track missing checks."}
          </p>
        ) : (
          <>
            {missingPaydays.length > 0 ? (
              <div className="mt-3 mb-4">
                <p className="text-sm font-medium text-warn">
                  {missingPaydays.length} missing paycheck
                  {missingPaydays.length === 1 ? "" : "s"}
                </p>
                <ul className="space-y-2 mt-2">
                  {missingPaydays.map((payday) => (
                    <li
                      key={payday}
                      className="flex items-center justify-between gap-3 py-2 divider-line last:border-0"
                    >
                      <div className="min-w-0">
                        <p className="text-body font-medium">
                          {formatIsoDate(payday)}
                        </p>
                        <p className="text-xs text-muted">Not logged</p>
                      </div>
                      <button
                        type="button"
                        className="btn-ghost text-xs py-1 px-2 shrink-0"
                        onClick={() => onLogMissingPaycheck(payday)}
                      >
                        Log
                      </button>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
            {logs.length > 0 ? (
              <>
                {missingPaydays.length > 0 ? (
                  <p className="text-sm font-medium text-muted mt-3 mb-2">Logged</p>
                ) : null}
                <ul className={clsx("space-y-2", missingPaydays.length === 0 && "mt-3")}>
                  {logs.map((entry) => (
                    <li
                      key={entry.id}
                      className="flex items-center justify-between gap-3 py-2 divider-line last:border-0"
                    >
                      <div className="min-w-0">
                        <p className="text-body font-medium">
                          {formatIsoDate(entry.payDate)}
                        </p>
                        <p className="text-xs text-muted truncate">
                          Gross {formatUsd(entry.grossPay)}
                          {entry.overtimeHours
                            ? ` · ${entry.overtimeHours} OT hrs`
                            : ""}
                          {entry.autoGenerated ? " · Estimated" : ""}
                          {entry.notes ? ` · ${entry.notes}` : ""}
                        </p>
                      </div>
                      <div className="text-right shrink-0 flex items-center gap-2">
                        <p className="money text-base">{formatUsd(entry.netPay)}</p>
                        <button
                          type="button"
                          className="btn-ghost text-xs py-1 px-2"
                          onClick={() => onEditLog(entry)}
                        >
                          Edit
                        </button>
                        <button
                          type="button"
                          className="btn-ghost text-xs py-1 px-2 text-error"
                          onClick={() => onDeleteLog(entry.id)}
                        >
                          Del
                        </button>
                      </div>
                    </li>
                  ))}
                </ul>
              </>
            ) : null}
          </>
        )}
      </section>

      <PayRateHistorySection
        payType={config.payType}
        history={config.payRateHistory ?? []}
        onChange={(list) => setConfig((c) => ({ ...c, payRateHistory: list }))}
        inferred={inferredPayRates}
        year={year}
      />

      <DirectDepositsSection
        deposits={config.directDeposits}
        allocations={calc.depositAllocations}
        netPay={calc.netPay}
        onChange={(list) => setConfig((c) => ({ ...c, directDeposits: list }))}
      />
        </>
      ) : null}
    </div>
  );
}

function WhatIfView({
  config,
  calc,
  setConfig,
  annualOvertimeHours,
  projection,
  baseline,
  onOvertimeChange,
  whatIfDeposits,
  whatIfDepositAllocations,
  whatIfDepositsCustomized,
  onWhatIfDepositsChange,
  onResetWhatIfDeposits,
  onLogPaycheck,
}: {
  config: ReturnType<typeof useSalaryData>["config"];
  calc: ReturnType<typeof useSalaryData>["calculation"];
  setConfig: ReturnType<typeof useSalaryData>["setConfig"];
  annualOvertimeHours: number;
  projection: ReturnType<typeof useSalaryData>["annualProjection"];
  baseline: ReturnType<typeof useSalaryData>["annualBaseline"];
  onOvertimeChange: (hours: number) => void;
  whatIfDeposits: DirectDeposit[];
  whatIfDepositAllocations: ReturnType<
    typeof useSalaryData
  >["whatIfDepositAllocations"];
  whatIfDepositsCustomized: boolean;
  onWhatIfDepositsChange: (deposits: DirectDeposit[]) => void;
  onResetWhatIfDeposits: () => void;
  onLogPaycheck: () => void;
}) {
  const otDelta = projection.annualOvertimePay - baseline.annualOvertimePay;

  return (
    <div className="space-y-4">
      <section className="card-quiet p-4 text-sm text-muted">
        <p>
          Changes here are hypothetical — they do not affect your Summary
          projections until you log real paychecks or update saved settings.
        </p>
      </section>

      <section className="card p-5 bg-dollar-gradient text-center">
        <p className="text-xs tracking-wider text-muted font-medium">
          Modeled Net (This Period)
        </p>
        <p className="money text-3xl mt-1">{formatUsd(calc.netPay)}</p>
        <div className="mt-4 flex justify-center gap-6 text-sm">
          <div>
            <p className="text-muted text-xs">Gross</p>
            <p className="money">{formatUsd(calc.grossPay)}</p>
          </div>
          <div>
            <p className="text-muted text-xs">Taxes</p>
            <p className="money">{formatUsd(calc.totalTaxes)}</p>
          </div>
          <div>
            <p className="text-muted text-xs">Modeled annual net</p>
            <p className="money">{formatUsd(projection.annualNetPay)}</p>
          </div>
        </div>
        <button
          type="button"
          className="btn-primary text-sm mt-4"
          onClick={onLogPaycheck}
        >
          Log this paycheck
        </button>
      </section>

      <section className="card p-5 space-y-4">
        <h2 className="section-title">Pay Rate & Hours</h2>
        <div className="flex gap-2">
          {(Object.keys(PAY_TYPE_LABELS) as PayType[]).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => setConfig((c) => ({ ...c, payType: t }))}
              className={clsx(
                "flex-1",
                config.payType === t ? "filter-chip-active" : "filter-chip",
              )}
            >
              {PAY_TYPE_LABELS[t]}
            </button>
          ))}
        </div>
        {config.payType === "SALARY" ? (
          <NumberField
            label="Annual salary"
            value={config.annualSalary ?? 0}
            onChange={(v) => setConfig((c) => ({ ...c, annualSalary: v }))}
            money
          />
        ) : (
          <NumberField
            label="Hourly rate"
            value={config.hourlyRate}
            onChange={(v) => setConfig((c) => ({ ...c, hourlyRate: v }))}
            money
          />
        )}
        <div className="grid grid-cols-2 gap-3">
          {config.payType === "SALARY" ? null : (
            <NumberField
              label="Standard hours"
              value={config.standardHoursPerPeriod}
              onChange={(v) =>
                setConfig((c) => ({ ...c, standardHoursPerPeriod: v }))
              }
            />
          )}
          <NumberField
            label="OT hours"
            value={config.overtimeHours}
            onChange={(v) => setConfig((c) => ({ ...c, overtimeHours: v }))}
          />
        </div>
        <NumberField
          label="OT multiplier"
          value={config.overtimeMultiplier}
          onChange={(v) =>
            setConfig((c) => ({ ...c, overtimeMultiplier: v }))
          }
        />
        {calc.overtimePay > 0 ? (
          <div className="flex justify-between text-sm">
            <span className="text-muted">Regular pay</span>
            <span className="money">{formatUsd(calc.regularPay)}</span>
          </div>
        ) : null}
        {calc.overtimePay > 0 ? (
          <div className="flex justify-between text-sm">
            <span className="text-muted">Overtime pay</span>
            <span className="money text-success">
              {formatUsd(calc.overtimePay)}
            </span>
          </div>
        ) : null}
      </section>

      <section className="card p-5 space-y-3">
        <h2 className="section-title">Withholding overrides</h2>
        <p className="text-xs text-muted">
          Filing status and state are set from the tax button above. Override any
          rate % here to match your actual stub (leave blank for estimated
          defaults).
        </p>
        <EditableTaxLine
          label="Federal income tax"
          amount={calc.federalTax}
          defaultRate={calc.federalMarginalRate}
          customRate={config.taxOverrides.customFederalTaxRate}
          exempt={config.taxOverrides.isExemptFromFederal}
          onExemptChange={(v) => updateTaxOverrides(setConfig, { isExemptFromFederal: v })}
          onRateChange={(v) =>
            updateTaxOverrides(setConfig, { customFederalTaxRate: v })
          }
        />
        <EditableTaxLine
          label="State income tax"
          amount={calc.stateTax}
          defaultRate={calc.stateTaxRate}
          customRate={config.taxOverrides.customStateTaxRate}
          exempt={config.taxOverrides.isExemptFromState}
          onExemptChange={(v) => updateTaxOverrides(setConfig, { isExemptFromState: v })}
          onRateChange={(v) =>
            updateTaxOverrides(setConfig, { customStateTaxRate: v })
          }
        />
        <EditableTaxLine
          label={config.county.trim() ? `${config.county} tax` : "County/local tax"}
          amount={calc.countyTax}
          defaultRate={calc.countyTaxRate}
          customRate={config.taxOverrides.customCountyTaxRate}
          exempt={config.taxOverrides.isExemptFromLocal}
          onExemptChange={(v) => updateTaxOverrides(setConfig, { isExemptFromLocal: v })}
          onRateChange={(v) =>
            updateTaxOverrides(setConfig, { customCountyTaxRate: v })
          }
        />
        <EditableTaxLine
          label="Social Security"
          amount={calc.socialSecurity}
          defaultRate={calc.socialSecurityRate}
          customRate={config.taxOverrides.customSocialSecurityRate}
          onRateChange={(v) =>
            updateTaxOverrides(setConfig, { customSocialSecurityRate: v })
          }
        />
        <EditableTaxLine
          label="Medicare"
          amount={calc.medicare}
          defaultRate={calc.medicareRate}
          customRate={config.taxOverrides.customMedicareRate}
          onRateChange={(v) =>
            updateTaxOverrides(setConfig, { customMedicareRate: v })
          }
        />
        <TaxLine label="Total taxes" amount={calc.totalTaxes} bold />
        <p className="text-xs text-muted">
          Effective rate: {formatPercent(calc.effectiveTaxRate)}
        </p>
      </section>

      <DeductionsSection
        title="Pre-Tax Deductions"
        deductions={config.preTaxDeductions}
        onChange={(list) =>
          setConfig((c) => ({ ...c, preTaxDeductions: list }))
        }
        isPreTax
      />
      <DeductionsSection
        title="Post-Tax Deductions"
        deductions={config.postTaxDeductions}
        onChange={(list) =>
          setConfig((c) => ({ ...c, postTaxDeductions: list }))
        }
        isPreTax={false}
      />

      <DirectDepositsSection
        deposits={whatIfDeposits}
        allocations={whatIfDepositAllocations}
        netPay={calc.netPay}
        onChange={onWhatIfDepositsChange}
        hint={
          whatIfDepositsCustomized
            ? "Custom projection splits — reset to match Summary anytime."
            : "Mirrors your Summary splits until you change amounts or percentages here."
        }
        onReset={whatIfDepositsCustomized ? onResetWhatIfDeposits : undefined}
      />

      <section className="card p-5 space-y-3">
        <h2 className="section-title">Annual Model</h2>
        <p className="text-sm text-muted">
          See how changes above would play out over a full year — useful for
          modeling raises, bonus pay, or annual overtime.
        </p>
        <NumberField
          label="OT hours for the year"
          value={annualOvertimeHours}
          onChange={onOvertimeChange}
        />
        {otDelta > 0 ? (
          <p className="text-sm text-success">
            +{formatUsd(otDelta)} gross from annual OT
          </p>
        ) : null}
        <div className="grid grid-cols-2 gap-3 pt-1">
          <Stat label="Modeled annual gross" value={formatUsd(projection.annualGrossPay)} />
          <Stat label="Modeled annual net" value={formatUsd(projection.annualNetPay)} />
          <Stat label="Modeled annual taxes" value={formatUsd(projection.annualTotalTaxes)} />
          <Stat
            label="Per paycheck net"
            value={formatUsd(projection.perPaycheckNet)}
          />
        </div>
      </section>

      <BreakdownCard
        title="Modeled Annual Taxes"
        lines={[
          { label: "Federal income tax", amount: projection.annualFederalTax },
          { label: "State income tax", amount: projection.annualStateTax },
          ...(projection.annualCountyTax > 0
            ? [{ label: "County/local tax", amount: projection.annualCountyTax }]
            : []),
          { label: "Social Security", amount: projection.annualSocialSecurity },
          { label: "Medicare", amount: projection.annualMedicare },
        ]}
        total={projection.annualTotalTaxes}
        negative
        footer={`Marginal federal ${formatPercent(
          projection.marginalFederalRate,
        )} · effective ${formatPercent(projection.effectiveTaxRate)}`}
      />

      {projection.preTaxDeductionBreakdown.length > 0 ? (
        <BreakdownCard
          title="Modeled Annual Pre-Tax Deductions"
          lines={projection.preTaxDeductionBreakdown.map((l) => ({
            label: l.name || "Pre-tax",
            amount: l.amount,
          }))}
          total={projection.annualPreTaxDeductions}
          negative
        />
      ) : null}
      {projection.postTaxDeductionBreakdown.length > 0 ? (
        <BreakdownCard
          title="Modeled Annual Post-Tax Deductions"
          lines={projection.postTaxDeductionBreakdown.map((l) => ({
            label: l.name || "Post-tax",
            amount: l.amount,
          }))}
          total={projection.annualPostTaxDeductions}
          negative
        />
      ) : null}
    </div>
  );
}

function PayRateHistorySection({
  payType,
  history,
  onChange,
  inferred,
  year,
}: {
  payType: PayType;
  history: PayRateChange[];
  onChange: (list: PayRateChange[]) => void;
  inferred?: ReturnType<typeof inferPayRatesFromLogs>;
  year?: number;
}) {
  const sorted = [...history]
    .filter((h) =>
      year == null
        ? true
        : new Date(h.effectiveDate).getFullYear() === year ||
          !h.id.startsWith("inferred-"),
    )
    .sort((a, b) => b.effectiveDate - a.effectiveDate);
  const inferredById = new Map(
    (inferred?.raises ?? []).map((r) => [r.id, r]),
  );
  const add = () => {
    onChange([
      ...history,
      {
        id: crypto.randomUUID(),
        effectiveDate: Date.now(),
        payType,
        hourlyRate: payType === "HOURLY" ? 0 : undefined,
        annualSalary: payType === "SALARY" ? 0 : undefined,
        note: "",
      },
    ]);
  };
  const update = (id: string, patch: Partial<PayRateChange>) =>
    onChange(history.map((h) => (h.id === id ? { ...h, ...patch } : h)));

  return (
    <section className="card p-5 space-y-3">
      <div className="flex items-center justify-between gap-2">
        <h2 className="section-title">Pay Rate History (Raises)</h2>
        <button type="button" className="btn-ghost text-sm py-1" onClick={add}>
          Add
        </button>
      </div>
      <p className="text-sm text-muted">
        Auto-filled from logged paychecks when regular pay increases. Starting
        pay comes from your first paycheck of the year; later bumps become
        raises with percent and per-paycheck change.
      </p>
      {inferred?.startingRate ? (
        <div className="card-quiet p-3 text-sm space-y-1">
          <p className="text-body font-medium">Starting pay ({year})</p>
          <p className="text-muted">
            From first paycheck on {formatIsoDate(inferred.startingRate.effectiveDate)}
            :{" "}
            <span className="money text-body">
              {formatUsd(inferred.startingRate.regularGrossPerPaycheck)}
            </span>{" "}
            per paycheck
            {inferred.startingRate.payType === "SALARY" ? (
              <>
                {" "}
                ·{" "}
                <span className="money text-body">
                  {formatUsd(inferred.startingRate.annualSalary ?? 0)}
                </span>{" "}
                annual
              </>
            ) : (
              <>
                {" "}
                ·{" "}
                <span className="money text-body">
                  {formatUsd(inferred.startingRate.hourlyRate)}
                </span>
                /hr
              </>
            )}
          </p>
        </div>
      ) : null}
      {sorted.length === 0 ? null : (
        <ul className="space-y-3">
          {sorted.map((h) => {
            const inferredRaise = inferredById.get(h.id);
            return (
            <li key={h.id} className="space-y-2 pb-3 divider-line last:border-0">
              {inferredRaise ? (
                <p className="text-xs text-success font-medium">
                  +{inferredRaise.percentIncrease.toFixed(1)}% raise · +
                  {formatUsd(inferredRaise.perPaycheckIncrease)} per paycheck
                </p>
              ) : null}
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="label">Effective date</label>
                  <input
                    className="input"
                    type="date"
                    value={
                      h.effectiveDate ? formatIsoDate(h.effectiveDate) : ""
                    }
                    onChange={(e) =>
                      update(h.id, {
                        effectiveDate:
                          parseIsoDate(e.target.value) ?? h.effectiveDate,
                      })
                    }
                  />
                </div>
                <NumberField
                  label={h.payType === "SALARY" ? "Annual salary" : "Hourly rate"}
                  value={
                    h.payType === "SALARY"
                      ? (h.annualSalary ?? 0)
                      : (h.hourlyRate ?? 0)
                  }
                  onChange={(v) =>
                    update(
                      h.id,
                      h.payType === "SALARY"
                        ? { annualSalary: v }
                        : { hourlyRate: v },
                    )
                  }
                  money
                />
              </div>
              <input
                className="input text-sm"
                value={h.note ?? ""}
                onChange={(e) => update(h.id, { note: e.target.value })}
                placeholder="Note (e.g. annual merit raise)"
              />
              <button
                type="button"
                className="btn-ghost text-xs text-error py-1"
                onClick={() => onChange(history.filter((x) => x.id !== h.id))}
              >
                Remove
              </button>
            </li>
            );
          })}
        </ul>
      )}
    </section>
  );
}

function updateTaxOverrides(
  setConfig: ReturnType<typeof useSalaryData>["setConfig"],
  patch: Partial<TaxOverrides>,
) {
  setConfig((c) => ({
    ...c,
    taxOverrides: { ...c.taxOverrides, ...patch },
  }));
}

function EditableTaxLine({
  label,
  amount,
  defaultRate,
  customRate,
  exempt,
  onExemptChange,
  onRateChange,
}: {
  label: string;
  amount: number;
  defaultRate: number;
  customRate?: number | null;
  exempt?: boolean;
  onExemptChange?: (exempt: boolean) => void;
  onRateChange: (rate: number | null) => void;
}) {
  return (
    <div className="flex items-center justify-between gap-2 text-sm py-1">
      <div className="min-w-0">
        <span className="text-muted">{label}</span>
        {onExemptChange ? (
          <label className="flex items-center gap-1.5 text-xs text-muted mt-0.5 cursor-pointer">
            <input
              type="checkbox"
              checked={Boolean(exempt)}
              onChange={(e) => onExemptChange(e.target.checked)}
            />
            Exempt
          </label>
        ) : null}
      </div>
      <div className="flex items-center gap-2 shrink-0">
        <span className="money">{formatUsd(amount)}</span>
        <PercentRateInput
          className="input w-20 text-xs py-1"
          defaultRate={defaultRate}
          value={customRate}
          disabled={exempt}
          onChange={onRateChange}
          aria-label={`${label} override rate`}
        />
      </div>
    </div>
  );
}

function depositSplitLabel(d: DirectDeposit): string {
  if (d.isRemainder) return "Remainder";
  if (d.isPercentage) return `${d.amount}% of net`;
  return formatUsd(d.amount);
}

function DirectDepositsSection({
  deposits,
  allocations,
  netPay,
  onChange,
  hint,
  onReset,
}: {
  deposits: DirectDeposit[];
  allocations: ReturnType<typeof useSalaryData>["calculation"]["depositAllocations"];
  netPay: number;
  onChange: (list: DirectDeposit[]) => void;
  hint?: string;
  onReset?: () => void;
}) {
  const [sheetOpen, setSheetOpen] = useState(false);
  const [editingDeposit, setEditingDeposit] = useState<DirectDeposit | null>(
    null,
  );

  const allocationById = new Map(
    allocations.map((a) => [a.deposit.id, a.calculatedAmount]),
  );
  const allocatedSum = allocations.reduce((s, a) => s + a.calculatedAmount, 0);
  const unallocated = netPay - allocatedSum;

  const openAdd = () => {
    setEditingDeposit(null);
    setSheetOpen(true);
  };

  const openEdit = (deposit: DirectDeposit) => {
    setEditingDeposit(deposit);
    setSheetOpen(true);
  };

  const closeSheet = () => {
    setSheetOpen(false);
    setEditingDeposit(null);
  };

  const saveDeposit = (draft: DirectDeposit) => {
    const exists = deposits.some((d) => d.id === draft.id);
    let next = exists
      ? deposits.map((d) => (d.id === draft.id ? draft : d))
      : [...deposits, { ...draft, sortOrder: deposits.length }];

    if (draft.isRemainder) {
      next = next.map((d) => ({
        ...d,
        isRemainder: d.id === draft.id,
      }));
    }

    onChange(next);
    closeSheet();
  };

  const removeDeposit = (id: string) => {
    onChange(deposits.filter((d) => d.id !== id));
  };

  const sorted = [...deposits].sort((a, b) => a.sortOrder - b.sortOrder);

  return (
    <section className="card p-5 space-y-3">
      <div className="flex items-center justify-between gap-2">
        <h2 className="section-title">Direct Deposits</h2>
        <div className="flex items-center gap-2 shrink-0">
          {onReset ? (
            <button
              type="button"
              className="btn-ghost text-xs py-1"
              onClick={onReset}
            >
              Reset to Summary
            </button>
          ) : null}
          <button type="button" className="btn-ghost text-sm py-1" onClick={openAdd}>
            Add
          </button>
        </div>
      </div>
      {hint ? <p className="text-xs text-muted">{hint}</p> : null}
      {sorted.length === 0 ? (
        <p className="text-sm text-muted">
          Split take-home pay across accounts (percent, fixed amount, or
          remainder).
        </p>
      ) : (
        <ul className="space-y-2">
          {sorted.map((d) => {
            const amount = allocationById.get(d.id);
            return (
              <li
                key={d.id}
                className="flex items-center justify-between gap-3 py-2 divider-line last:border-0"
              >
                <div className="min-w-0 flex-1">
                  <p className="text-body font-medium truncate">
                    {d.accountName || "Untitled account"}
                  </p>
                  <p className="text-xs text-muted truncate">
                    {[d.bankName, depositSplitLabel(d)]
                      .filter(Boolean)
                      .join(" · ")}
                  </p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  {amount != null ? (
                    <span className="money text-base">{formatUsd(amount)}</span>
                  ) : null}
                  <button
                    type="button"
                    className="btn-ghost text-xs py-1 px-2"
                    onClick={() => openEdit(d)}
                  >
                    Edit
                  </button>
                  <button
                    type="button"
                    className="btn-ghost text-xs py-1 px-2 text-error"
                    onClick={() => removeDeposit(d.id)}
                  >
                    Del
                  </button>
                </div>
              </li>
            );
          })}
          {unallocated > 0.01 ? (
            <li className="flex items-center justify-between gap-3 py-2 border-t border-border">
              <p className="text-sm font-medium text-warn">Unallocated</p>
              <span className="money text-warn">{formatUsd(unallocated)}</span>
            </li>
          ) : null}
        </ul>
      )}

      <DirectDepositSheet
        open={sheetOpen}
        deposit={editingDeposit}
        depositCount={deposits.length}
        onClose={closeSheet}
        onSave={saveDeposit}
      />
    </section>
  );
}

function SegmentedBar<T extends string>({
  options,
  value,
  onChange,
  ariaLabel,
  className,
}: {
  options: { id: T; label: string }[];
  value: T;
  onChange: (id: T) => void;
  ariaLabel: string;
  className?: string;
}) {
  return (
    <div
      className={clsx(
        "flex gap-1 p-1 rounded-lg bg-surfaceVariant/80",
        className,
      )}
      role="tablist"
      aria-label={ariaLabel}
    >
      {options.map((option) => (
        <button
          key={option.id}
          type="button"
          role="tab"
          aria-selected={value === option.id}
          onClick={() => onChange(option.id)}
          className={clsx(
            "flex-1 text-xs sm:text-sm py-2 px-2 rounded-md font-medium transition-colors",
            value === option.id
              ? "bg-surface text-heading shadow-sm"
              : "text-muted hover:text-body",
          )}
        >
          {option.label}
        </button>
      ))}
    </div>
  );
}

function FederalTaxReturnSection({
  projection,
  filingStatus,
}: {
  projection: FederalTaxReturnProjection;
  filingStatus: keyof typeof FILING_STATUS_LABELS;
}) {
  if (projection.annualGross <= 0) {
    return (
      <section className="card p-5">
        <h2 className="section-title">Projected Federal Return</h2>
        <p className="text-sm text-muted mt-1">
          Set your pay rate and tax info to estimate federal withholding vs tax
          owed.
        </p>
      </section>
    );
  }

  const refund = projection.refundOrBalance;
  const outcome =
    refund > 1
      ? { label: "Estimated refund", amount: refund, positive: true }
      : refund < -1
        ? { label: "Estimated balance due", amount: Math.abs(refund), positive: false }
        : { label: "On track", amount: 0, positive: true };

  return (
    <section className="card p-5">
      <h2 className="section-title">Projected Federal Return</h2>
      <p className="text-sm text-muted mt-1">
        W-2 estimate for {FILING_STATUS_LABELS[filingStatus]} using the standard
        deduction. Excludes credits, other income, and itemized deductions.
      </p>

      <div className="mt-4 card-quiet p-4 text-center">
        <p className="text-xs text-muted tracking-wide uppercase">
          {outcome.label}
        </p>
        {outcome.amount > 0 ? (
          <p
            className={clsx(
              "money text-3xl mt-1",
              outcome.positive ? "text-primary" : "text-error",
            )}
          >
            {formatUsd(outcome.amount)}
          </p>
        ) : (
          <p className="money text-3xl mt-1 text-primary">—</p>
        )}
      </div>

      <div className="mt-4 space-y-2">
        <ReturnLine label="Projected wages" amount={projection.annualGross} />
        {projection.annualPreTaxDeductions > 0 ? (
          <ReturnLine
            label="Pre-tax deductions"
            amount={projection.annualPreTaxDeductions}
            negative
          />
        ) : null}
        <ReturnLine
          label="Adjusted gross income"
          amount={projection.adjustedGrossIncome}
          bold
        />
        <ReturnLine
          label={`Standard deduction (${FILING_STATUS_LABELS[filingStatus]})`}
          amount={projection.standardDeduction}
          negative
        />
        <ReturnLine
          label="Federal taxable income"
          amount={projection.federalTaxableIncome}
          bold
        />
        <div className="border-t border-border pt-2 mt-2 space-y-2">
          <ReturnLine
            label="Estimated federal tax owed"
            amount={projection.estimatedFederalTaxOwed}
          />
          <ReturnLine
            label="Federal tax withheld"
            amount={projection.federalWithheld}
          />
        </div>
      </div>
    </section>
  );
}

function ReturnLine({
  label,
  amount,
  negative = false,
  bold = false,
}: {
  label: string;
  amount: number;
  negative?: boolean;
  bold?: boolean;
}) {
  return (
    <div className="flex justify-between gap-2 text-sm">
      <span className={bold ? "text-body font-medium" : "text-muted"}>
        {label}
      </span>
      <span
        className={clsx(
          "money shrink-0",
          bold && "font-semibold",
          negative && amount > 0 && "text-error",
        )}
      >
        {negative && amount > 0 ? "−" : ""}
        {formatUsd(amount)}
      </span>
    </div>
  );
}

function BreakdownCard({
  title,
  lines,
  total,
  negative = false,
  footer,
}: {
  title: string;
  lines: YtdBreakdownLine[];
  total: number;
  negative?: boolean;
  footer?: string;
}) {
  if (lines.length === 0) return null;
  return (
    <section className="card p-5">
      <div className="flex items-center justify-between gap-2">
        <h2 className="section-title">{title}</h2>
        <span className={clsx("money font-semibold", negative && "text-error")}>
          {negative ? "−" : ""}
          {formatUsd(total)}
        </span>
      </div>
      <ul className="mt-3 space-y-1.5">
        {lines.map((line) => (
          <li
            key={line.label}
            className="flex items-center justify-between gap-2 text-sm"
          >
            <span className="text-muted truncate">
              {line.label}
              {line.hours ? (
                <span className="text-xs"> · {line.hours.toFixed(1)} hrs</span>
              ) : null}
            </span>
            <span className={clsx("money shrink-0", negative && "text-error")}>
              {negative ? "−" : ""}
              {formatUsd(line.amount)}
            </span>
          </li>
        ))}
      </ul>
      {footer ? (
        <p className="text-xs text-muted mt-3 border-t border-border pt-2">
          {footer}
        </p>
      ) : null}
    </section>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="card-quiet p-4">
      <p className="text-xs text-muted">{label}</p>
      <p className="money text-xl mt-1">{value}</p>
    </div>
  );
}

function TaxLine({
  label,
  amount,
  bold = false,
}: {
  label: string;
  amount: number;
  bold?: boolean;
}) {
  return (
    <div className="flex justify-between text-sm">
      <span className={bold ? "text-body font-medium" : "text-muted"}>
        {label}
      </span>
      <span className={clsx("money", bold && "font-semibold")}>
        {formatUsd(amount)}
      </span>
    </div>
  );
}

function decimalDisplayValue(n: number): string {
  return n === 0 ? "" : String(n);
}

function percentDisplayValue(rate: number | null | undefined): string {
  if (rate == null) return "";
  const pct = rate * 100;
  return pct === 0 ? "" : String(pct);
}

function PercentRateInput({
  value,
  onChange,
  defaultRate,
  disabled,
  className,
  "aria-label": ariaLabel,
}: {
  value: number | null | undefined;
  onChange: (rate: number | null) => void;
  defaultRate: number;
  disabled?: boolean;
  className?: string;
  "aria-label"?: string;
}) {
  const [text, setText] = useState(() => percentDisplayValue(value));

  useEffect(() => {
    setText((prev) => {
      const parsed = Number.parseFloat(prev);
      if (
        prev !== "" &&
        prev !== "." &&
        Number.isFinite(parsed) &&
        value != null &&
        Math.abs(parsed / 100 - value) < 1e-9
      ) {
        return prev;
      }
      if (prev === "" && (value == null || value === 0)) return prev;
      return percentDisplayValue(value);
    });
  }, [value]);

  return (
    <input
      className={className}
      inputMode="decimal"
      placeholder={`${(defaultRate * 100).toFixed(1)}%`}
      value={text}
      disabled={disabled}
      aria-label={ariaLabel}
      onChange={(e) => {
        const raw = e.target.value;
        if (raw !== "" && !/^\d*\.?\d*$/.test(raw)) return;
        setText(raw);
        if (raw === "" || raw === ".") {
          onChange(null);
          return;
        }
        const n = Number.parseFloat(raw);
        if (Number.isFinite(n)) onChange(n / 100);
      }}
      onBlur={() => {
        if (text === "" || text === ".") {
          setText("");
          onChange(null);
          return;
        }
        const n = Number.parseFloat(text);
        if (Number.isFinite(n)) {
          onChange(n / 100);
          setText(String(n));
        } else {
          setText("");
          onChange(null);
        }
      }}
    />
  );
}

function DecimalInput({
  value,
  onChange,
  className,
  placeholder,
}: {
  value: number;
  onChange: (n: number) => void;
  className?: string;
  placeholder?: string;
}) {
  const [text, setText] = useState(() => decimalDisplayValue(value));

  useEffect(() => {
    setText((prev) => {
      const parsed = Number.parseFloat(prev);
      if (prev !== "" && prev !== "." && Number.isFinite(parsed) && parsed === value) {
        return prev;
      }
      return decimalDisplayValue(value);
    });
  }, [value]);

  return (
    <input
      className={className}
      inputMode="decimal"
      placeholder={placeholder}
      value={text}
      onChange={(e) => {
        const raw = e.target.value;
        if (raw !== "" && !/^\d*\.?\d*$/.test(raw)) return;
        setText(raw);
        if (raw === "" || raw === ".") {
          onChange(0);
          return;
        }
        const n = Number.parseFloat(raw);
        if (Number.isFinite(n)) onChange(n);
      }}
      onBlur={() => {
        const n = Number.parseFloat(text);
        setText(Number.isFinite(n) ? String(n) : "");
        if (Number.isFinite(n)) onChange(n);
        else onChange(0);
      }}
    />
  );
}

function NumberField({
  label,
  value,
  onChange,
  money = false,
}: {
  label: string;
  value: number;
  onChange: (v: number) => void;
  money?: boolean;
}) {
  return (
    <div>
      <label className="label">{label}</label>
      <DecimalInput
        className={clsx("input", money && "money")}
        value={value}
        onChange={onChange}
      />
    </div>
  );
}

function DeductionRow({
  deduction,
  isPreTax,
  autoFocusName,
  onNameFocused,
  onChange,
  onRemove,
}: {
  deduction: ReturnType<
    typeof useSalaryData
  >["config"]["preTaxDeductions"][number];
  isPreTax: boolean;
  autoFocusName: boolean;
  onNameFocused: () => void;
  onChange: (next: ReturnType<
    typeof useSalaryData
  >["config"]["preTaxDeductions"][number]) => void;
  onRemove: () => void;
}) {
  const nameRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (!autoFocusName) return;
    nameRef.current?.focus();
    onNameFocused();
  }, [autoFocusName, onNameFocused]);

  return (
    <li className="space-y-2 pb-3 divider-line last:border-0">
      <input
        ref={nameRef}
        className="input"
        value={deduction.name}
        onChange={(e) => onChange({ ...deduction, name: e.target.value })}
        placeholder={isPreTax ? "e.g. 401(k)" : "e.g. Union dues"}
      />
      <div className="grid grid-cols-2 gap-2">
        <DecimalInput
          className="input money"
          value={deduction.amount}
          placeholder="0.00"
          onChange={(amount) => onChange({ ...deduction, amount })}
        />
        <label className="flex items-center gap-2 text-sm text-muted px-1">
          <input
            type="checkbox"
            checked={deduction.isPercentage}
            onChange={(e) =>
              onChange({ ...deduction, isPercentage: e.target.checked })
            }
          />
          % of gross
        </label>
      </div>
      <button
        type="button"
        className="btn-ghost text-xs text-error py-1"
        onClick={onRemove}
      >
        Remove
      </button>
    </li>
  );
}

function DeductionsSection({
  title,
  deductions,
  onChange,
  isPreTax,
}: {
  title: string;
  deductions: ReturnType<typeof useSalaryData>["config"]["preTaxDeductions"];
  onChange: (
    list: ReturnType<typeof useSalaryData>["config"]["preTaxDeductions"],
  ) => void;
  isPreTax: boolean;
}) {
  const [focusNameId, setFocusNameId] = useState<string | null>(null);

  const add = () => {
    const id = crypto.randomUUID();
    setFocusNameId(id);
    onChange([
      ...deductions,
      {
        id,
        name: "",
        amount: 0,
        isPercentage: false,
        isEnabled: true,
        type: isPreTax ? "PRE_TAX" : "POST_TAX",
      },
    ]);
  };

  return (
    <section className="card p-5 space-y-3">
      <div className="flex items-center justify-between gap-2">
        <h2 className="section-title">{title}</h2>
        <button type="button" className="btn-ghost text-sm py-1" onClick={add}>
          Add
        </button>
      </div>
      {deductions.length === 0 ? (
        <p className="text-sm text-muted">None configured.</p>
      ) : (
        <ul className="space-y-3">
          {deductions.map((d) => (
            <DeductionRow
              key={d.id}
              deduction={d}
              isPreTax={isPreTax}
              autoFocusName={d.id === focusNameId}
              onNameFocused={() => setFocusNameId(null)}
              onChange={(next) =>
                onChange(deductions.map((x) => (x.id === d.id ? next : x)))
              }
              onRemove={() => onChange(deductions.filter((x) => x.id !== d.id))}
            />
          ))}
        </ul>
      )}
    </section>
  );
}
