package com.fiatlife.app.domain.model

import kotlinx.serialization.Serializable
import java.util.Calendar
import java.util.UUID

/** A single editable money line on a logged paystub (earning, tax, or deduction). */
@Serializable
data class PaycheckLineItem(
    val id: String = "",
    val label: String = "",
    val amount: Double = 0.0,
    /** Hours, only meaningful for earnings lines like Regular/Overtime. */
    val hours: Double? = null
)

/** An effective-dated pay-rate change (raise). */
@Serializable
data class PayRateChange(
    val id: String = "",
    val effectiveDate: Long = 0L,
    val payType: PayType? = null,
    val hourlyRate: Double? = null,
    val annualSalary: Double? = null,
    val standardHoursPerPeriod: Double? = null,
    val note: String? = null
)

/** A logged actual paycheck with an itemized breakdown. */
@Serializable
data class PaycheckLogEntry(
    val id: String = "",
    val payDate: Long = 0L,
    val grossPay: Double = 0.0,
    val netPay: Double = 0.0,
    val totalTaxes: Double? = null,
    val totalPreTaxDeductions: Double? = null,
    val totalPostTaxDeductions: Double? = null,
    val overtimeHours: Double? = null,
    val notes: String? = null,
    val earnings: List<PaycheckLineItem> = emptyList(),
    val taxes: List<PaycheckLineItem> = emptyList(),
    val preTaxDeductions: List<PaycheckLineItem> = emptyList(),
    val postTaxDeductions: List<PaycheckLineItem> = emptyList(),
    val employerContributions: List<PaycheckLineItem> = emptyList(),
    val attachmentHash: String? = null,
    val attachmentLabel: String? = null,
    /** True when created via bulk "Generate missing" from calculator estimates. */
    val autoGenerated: Boolean? = null
)

data class EffectiveRate(
    val payType: PayType,
    val hourlyRate: Double,
    val annualSalary: Double,
    val standardHoursPerPeriod: Double
)

data class YtdBreakdownLine(
    val label: String,
    val amount: Double,
    val hours: Double = 0.0
)

/** Full-year projection from logged YTD actuals + latest pay rate for remaining periods. */
data class AnnualExtrapolation(
    val source: Source,
    val basedOnPaychecks: Int,
    val scheduledPaychecksInYear: Int,
    val remainingPaychecksProjected: Int = 0,
    /** Past paydays with no log, included in [remainingPaychecksProjected]. */
    val unloggedPastPaychecks: Int = 0,
    val averageOvertimeHoursPerPaycheck: Double = 0.0,
    val projectOvertimeForward: Boolean = true,
    /** Overtime rate ÷ regular rate (from paystubs when they itemize hours). */
    val overtimeMultiplier: Double = 1.5,
    val annualGrossPay: Double,
    val annualNetPay: Double,
    val annualTotalTaxes: Double,
    val annualTotalDeductions: Double,
    val annualPreTaxDeductions: Double,
    val annualPostTaxDeductions: Double,
    val overtimeHours: Double,
    val perPaycheckNet: Double,
    val perPaycheckGross: Double,
    val earnings: List<YtdBreakdownLine>,
    val taxes: List<YtdBreakdownLine>,
    val preTaxDeductions: List<YtdBreakdownLine>,
    val postTaxDeductions: List<YtdBreakdownLine>,
    val employerContributions: List<YtdBreakdownLine>,
    val effectiveTaxRate: Double
) {
    enum class Source { LOGGED, ESTIMATED }
}

enum class MonthlyTakeHomeSource { LOGGED, ESTIMATED, MIXED }

/** Monthly take-home from logged paychecks plus base-rate remainder (no OT projected). */
data class MonthlyTakeHomeProjection(
    val totalTakeHome: Double,
    val totalGross: Double,
    val totalTaxes: Double,
    val totalDeductions: Double,
    val loggedTakeHome: Double,
    val loggedGross: Double,
    val loggedTaxes: Double,
    val loggedDeductions: Double,
    val projectedRemainder: Double,
    val projectedGross: Double,
    val projectedTaxes: Double,
    val projectedDeductions: Double,
    val perPaycheckNet: Double,
    val loggedPaycheckCount: Int,
    val remainingPaycheckCount: Int,
    val scheduledPaychecksInMonth: Int,
    val loggedOvertimeHours: Double,
    val loggedBonusTotal: Double,
    val source: MonthlyTakeHomeSource
)

/** Rough federal Form 1040 estimate from projected annual wages and withholding. */
data class FederalTaxReturnProjection(
    val annualGross: Double,
    val annualPreTaxDeductions: Double,
    val adjustedGrossIncome: Double,
    val standardDeduction: Double,
    /** "No tax on overtime" deduction (2025–2028). */
    val overtimeDeduction: Double = 0.0,
    val federalTaxableIncome: Double,
    val estimatedFederalTaxOwed: Double,
    val federalWithheld: Double,
    /** Positive = estimated refund; negative = estimated balance due. */
    val refundOrBalance: Double,
    /** Logged paystubs with taxes but no line recognizable as federal income tax. */
    val paychecksMissingFederalLine: Int = 0
)

data class YtdSummary(
    val year: Int,
    val source: Source,
    val paycheckCount: Int,
    val scheduledPaychecksYtd: Int,
    val scheduledPaychecksInYear: Int,
    val grossPay: Double,
    val netPay: Double,
    val totalTaxes: Double,
    val totalPreTaxDeductions: Double,
    val totalPostTaxDeductions: Double,
    val overtimeHours: Double,
    val earnings: List<YtdBreakdownLine>,
    val taxes: List<YtdBreakdownLine>,
    val preTaxDeductions: List<YtdBreakdownLine>,
    val postTaxDeductions: List<YtdBreakdownLine>,
    val employerContributions: List<YtdBreakdownLine>,
    val annualExtrapolation: AnnualExtrapolation,
    val annualNetTarget: Double,
    val progressPercent: Double,
    val remainingPaychecks: Int,
    val expectedNetToDate: Double,
    val netVariance: Double,
    val projectedAnnualTaxes: Double
) {
    enum class Source { LOGGED, ESTIMATED }
}

/**
 * Year-to-date earnings/tax/deduction aggregation. Mirrors the web `summarizeYtd`
 * so both platforms present the same itemized summary.
 */
object SalarySummary {

    fun newId(): String = UUID.randomUUID().toString()

    /** The pay rate in effect at [whenMs], resolved from base config + raise history. */
    fun effectiveRateAt(config: SalaryConfig, whenMs: Long): EffectiveRate {
        val base = EffectiveRate(
            payType = config.payType,
            hourlyRate = config.hourlyRate,
            annualSalary = config.annualSalary,
            standardHoursPerPeriod = config.standardHoursPerPeriod
        )
        val applicable = config.payRateHistory
            .filter { it.effectiveDate <= whenMs }
            .maxByOrNull { it.effectiveDate }
            ?: return base
        return EffectiveRate(
            payType = applicable.payType ?: base.payType,
            hourlyRate = applicable.hourlyRate ?: base.hourlyRate,
            annualSalary = applicable.annualSalary ?: base.annualSalary,
            standardHoursPerPeriod = applicable.standardHoursPerPeriod
                ?: base.standardHoursPerPeriod
        )
    }

    fun periodRegularGross(rate: EffectiveRate, frequency: PayFrequency): Double {
        return if (rate.payType == PayType.SALARY) {
            rate.annualSalary / frequency.periodsPerYear
        } else {
            rate.hourlyRate * rate.standardHoursPerPeriod
        }
    }

    fun monthBoundsFromAnchor(monthAnchorMillis: Long): Pair<Long, Long> {
        val start = Calendar.getInstance().apply {
            timeInMillis = monthAnchorMillis
            set(Calendar.DAY_OF_MONTH, 1)
            set(Calendar.HOUR_OF_DAY, 0)
            set(Calendar.MINUTE, 0)
            set(Calendar.SECOND, 0)
            set(Calendar.MILLISECOND, 0)
        }.timeInMillis
        val end = Calendar.getInstance().apply {
            timeInMillis = start
            add(Calendar.MONTH, 1)
            add(Calendar.MILLISECOND, -1)
        }.timeInMillis
        return start to end
    }

    fun scheduledPaydaysInMonth(
        config: SalaryConfig,
        monthAnchorMillis: Long
    ): List<Long> {
        val (start, end) = monthBoundsFromAnchor(monthAnchorMillis)
        val year = yearOf(monthAnchorMillis)
        val anchor = resolvePaydayAnchor(config, year, end)
            ?: config.firstPaydayOfYearMillis
            ?: if (config.payFrequency == PayFrequency.WEEKLY ||
                config.payFrequency == PayFrequency.BIWEEKLY
            ) {
                null
            } else {
                yearStart(year)
            }
            ?: return emptyList()
        return enumeratePaydays(anchor, config.payFrequency, start, end)
    }

    fun paycheckCountInMonth(
        config: SalaryConfig?,
        monthAnchorMillis: Long = System.currentTimeMillis()
    ): Int {
        if (config == null) return 0
        val scheduled = scheduledPaydaysInMonth(config, monthAnchorMillis)
        if (scheduled.isNotEmpty()) return scheduled.size
        return when (config.payFrequency) {
            PayFrequency.SEMIMONTHLY -> 2
            PayFrequency.MONTHLY -> 1
            else -> {
                val anchor = config.firstPaydayOfYearMillis ?: return 0
                val (start, end) = monthBoundsFromAnchor(monthAnchorMillis)
                countPaychecksInRange(anchor, config.payFrequency, start, end)
                    .coerceAtLeast(1)
            }
        }
    }

    fun computeMonthlyTakeHome(
        config: SalaryConfig,
        monthAnchorMillis: Long = System.currentTimeMillis(),
        asOf: Long = System.currentTimeMillis()
    ): MonthlyTakeHomeProjection {
        val (monthStart, monthEnd) = monthBoundsFromAnchor(monthAnchorMillis)
        val logs = config.paycheckLog
            .filter { it.payDate in monthStart..monthEnd }
            .sortedBy { it.payDate }

        val loggedTakeHome = logs.sumOf { it.netPay }
        val loggedGross = logs.sumOf { it.grossPay }
        val loggedTaxes = logs.sumOf { it.totalTaxes ?: 0.0 }
        val loggedPreTax = logs.sumOf { it.totalPreTaxDeductions ?: 0.0 }
        val loggedPostTax = logs.sumOf { it.totalPostTaxDeductions ?: 0.0 }
        val loggedDeductions = loggedPreTax + loggedPostTax
        val loggedOvertimeHours = logs.sumOf { entryOvertimeHours(it) }
        val loggedBonusTotal = logs.sumOf { entry ->
            entry.earnings
                .filter { it.label.trim().contains("bonus", ignoreCase = true) }
                .sumOf { it.amount }
        }
        val loggedDays = logs.map { startOfDay(it.payDate) }.toSet()

        val baseCalc = PaycheckCalculator.calculate(
            config.copy(overtimeHours = 0.0),
            asOf
        )
        val perPaycheckNet = baseCalc.netPay

        val scheduled = scheduledPaydaysInMonth(config, monthAnchorMillis)
        val scheduledCount = if (scheduled.isNotEmpty()) {
            scheduled.size
        } else {
            paycheckCountInMonth(config, monthAnchorMillis)
        }

        val remainingCount = if (scheduled.isNotEmpty()) {
            scheduled.count { startOfDay(it) !in loggedDays }
        } else {
            (scheduledCount - logs.size).coerceAtLeast(0)
        }

        val projectedRemainder = remainingCount * perPaycheckNet
        val projectedGross = remainingCount * baseCalc.grossPay
        val projectedTaxes = remainingCount * baseCalc.totalTaxes
        val projectedDeductions = remainingCount *
            (baseCalc.totalPreTaxDeductions + baseCalc.totalPostTaxDeductions)

        val source = when {
            logs.isNotEmpty() && remainingCount == 0 -> MonthlyTakeHomeSource.LOGGED
            logs.isNotEmpty() && remainingCount > 0 -> MonthlyTakeHomeSource.MIXED
            else -> MonthlyTakeHomeSource.ESTIMATED
        }

        return MonthlyTakeHomeProjection(
            totalTakeHome = loggedTakeHome + projectedRemainder,
            totalGross = loggedGross + projectedGross,
            totalTaxes = loggedTaxes + projectedTaxes,
            totalDeductions = loggedDeductions + projectedDeductions,
            loggedTakeHome = loggedTakeHome,
            loggedGross = loggedGross,
            loggedTaxes = loggedTaxes,
            loggedDeductions = loggedDeductions,
            projectedRemainder = projectedRemainder,
            projectedGross = projectedGross,
            projectedTaxes = projectedTaxes,
            projectedDeductions = projectedDeductions,
            perPaycheckNet = perPaycheckNet,
            loggedPaycheckCount = logs.size,
            remainingPaycheckCount = remainingCount,
            scheduledPaychecksInMonth = scheduledCount,
            loggedOvertimeHours = loggedOvertimeHours,
            loggedBonusTotal = loggedBonusTotal,
            source = source
        )
    }

    /**
     * Rough Form 1040 estimate: wages minus pre-tax deductions, the standard
     * deduction and the overtime-premium deduction, through that year's brackets.
     * Ignores credits, other income and itemizing.
     */
    fun projectFederalTaxReturn(
        config: SalaryConfig,
        annual: AnnualExtrapolation,
        year: Int = yearOf(System.currentTimeMillis())
    ): FederalTaxReturnProjection {
        val annualGross = annual.annualGrossPay
        val annualPreTax = annual.annualPreTaxDeductions
        val adjustedGrossIncome = annualGross - annualPreTax
        val standardDeduction = FederalTaxTables.standardDeduction(config.filingStatus, year)
        val overtimeDeduction = FederalTaxTables.overtimeDeduction(
            overtimePremium(annual.earnings, annual.overtimeMultiplier),
            adjustedGrossIncome,
            config.filingStatus,
            year
        )
        val federalTaxableIncome =
            (adjustedGrossIncome - standardDeduction - overtimeDeduction).coerceAtLeast(0.0)
        val estimatedFederalTaxOwed =
            FederalTaxTables.calculateTax(federalTaxableIncome, config.filingStatus, year)

        val federalWithheld = annual.taxes
            .filter { classifyTaxLine(it.label) == TaxLineKind.FEDERAL }
            .sumOf { it.amount }
        val paychecksMissingFederalLine = logsForYear(config, year).count { e ->
            (e.totalTaxes ?: 0.0) > 0.0 &&
                entryTaxes(e).none { classifyTaxLine(it.label) == TaxLineKind.FEDERAL }
        }

        return FederalTaxReturnProjection(
            annualGross = annualGross,
            annualPreTaxDeductions = annualPreTax,
            adjustedGrossIncome = adjustedGrossIncome,
            standardDeduction = standardDeduction,
            overtimeDeduction = overtimeDeduction,
            federalTaxableIncome = federalTaxableIncome,
            estimatedFederalTaxOwed = estimatedFederalTaxOwed,
            federalWithheld = federalWithheld,
            refundOrBalance = federalWithheld - estimatedFederalTaxOwed,
            paychecksMissingFederalLine = paychecksMissingFederalLine
        )
    }

    fun logsForYear(config: SalaryConfig, year: Int): List<PaycheckLogEntry> {
        return config.paycheckLog
            .filter { yearOf(it.payDate) == year }
            .sortedByDescending { it.payDate }
    }

    private fun payPeriodStepDays(frequency: PayFrequency): Int? = when (frequency) {
        PayFrequency.WEEKLY -> 7
        PayFrequency.BIWEEKLY -> 14
        else -> null
    }

    /** Calendar-day step (keeps local midnight across daylight-saving changes). */
    private fun addDays(ms: Long, days: Int): Long =
        Calendar.getInstance().apply {
            timeInMillis = ms
            add(Calendar.DAY_OF_MONTH, days)
        }.timeInMillis

    /**
     * Best anchor for scheduled payday enumeration. For weekly/biweekly pay, prefers an
     * anchor that matches logged paycheck dates (including when first payday was set
     * after logging or set to a nearby but incorrect date).
     */
    fun resolvePaydayAnchor(
        config: SalaryConfig,
        year: Int,
        asOf: Long = System.currentTimeMillis()
    ): Long? {
        val freq = config.payFrequency
        if (freq != PayFrequency.WEEKLY && freq != PayFrequency.BIWEEKLY) {
            return config.firstPaydayOfYearMillis ?: yearStart(year)
        }

        val loggedDays = logsForYear(config, year)
            .map { startOfDay(it.payDate) }
            .filter { it <= startOfDay(asOf) }
        if (loggedDays.isEmpty()) {
            return config.firstPaydayOfYearMillis
        }

        val stepDays = payPeriodStepDays(freq)!!
        val rangeEnd = minOf(asOf, yearEnd(year))
        val rangeStart = yearStart(year)
        val configured = config.firstPaydayOfYearMillis?.let { startOfDay(it) }

        val candidates = linkedSetOf<Long>()
        configured?.let { candidates.add(it) }
        for (logged in loggedDays) {
            candidates.add(logged)
            for (k in 0 until 30) {
                candidates.add(addDays(logged, -k * stepDays))
            }
        }

        var bestAnchor: Long? = null
        var bestScore = -1
        var bestPreferConfigured = false

        for (anchor in candidates) {
            val scheduled = enumeratePaydays(anchor, freq, rangeStart, rangeEnd).toSet()
            val matched = loggedDays.count { it in scheduled }
            val preferConfigured = configured != null && anchor == configured
            if (matched > bestScore || (matched == bestScore && preferConfigured && !bestPreferConfigured)) {
                bestScore = matched
                bestAnchor = anchor
                bestPreferConfigured = preferConfigured
            }
        }

        return bestAnchor
    }

    /** Whether scheduled paydays can be compared to the log for this pay frequency. */
    fun canDetectMissingPaychecks(config: SalaryConfig, year: Int? = null): Boolean =
        when (config.payFrequency) {
            PayFrequency.WEEKLY, PayFrequency.BIWEEKLY ->
                config.firstPaydayOfYearMillis != null ||
                    (year != null && logsForYear(config, year).isNotEmpty())
            else -> true
        }

    /** Scheduled paydays in [year] through [asOf] that have no matching log entry. */
    fun missingPaydaysForYear(
        config: SalaryConfig,
        year: Int,
        asOf: Long = System.currentTimeMillis()
    ): List<Long> {
        if (!canDetectMissingPaychecks(config, year)) return emptyList()
        val anchor = resolvePaydayAnchor(config, year, asOf) ?: return emptyList()
        val scheduled = enumeratePaydays(
            anchor,
            config.payFrequency,
            yearStart(year),
            minOf(asOf, yearEnd(year))
        )
        if (scheduled.isEmpty()) return emptyList()
        val loggedDays = logsForYear(config, year).map { startOfDay(it.payDate) }.toSet()
        return scheduled.filter { it !in loggedDays }
    }

    fun yearOf(ms: Long): Int {
        val cal = Calendar.getInstance().apply { timeInMillis = ms }
        return cal.get(Calendar.YEAR)
    }

    fun yearStart(year: Int): Long =
        Calendar.getInstance().apply {
            clear(); set(year, Calendar.JANUARY, 1, 0, 0, 0)
        }.timeInMillis

    fun yearEnd(year: Int): Long =
        Calendar.getInstance().apply {
            clear(); set(year, Calendar.DECEMBER, 31, 23, 59, 59)
        }.timeInMillis

    private fun startOfDay(ms: Long): Long =
        Calendar.getInstance().apply {
            timeInMillis = ms
            set(Calendar.HOUR_OF_DAY, 0); set(Calendar.MINUTE, 0)
            set(Calendar.SECOND, 0); set(Calendar.MILLISECOND, 0)
        }.timeInMillis

    fun countPaychecksInRange(
        firstPaydayMillis: Long,
        frequency: PayFrequency,
        rangeStart: Long,
        rangeEnd: Long
    ): Int = enumeratePaydays(firstPaydayMillis, frequency, rangeStart, rangeEnd).size

    fun enumeratePaydays(
        firstPaydayMillis: Long,
        frequency: PayFrequency,
        rangeStart: Long,
        rangeEnd: Long
    ): List<Long> {
        val days = mutableListOf<Long>()
        when (frequency) {
            PayFrequency.SEMIMONTHLY -> {
                val cursor = Calendar.getInstance().apply {
                    timeInMillis = rangeStart
                    set(Calendar.DAY_OF_MONTH, 1)
                }
                while (cursor.timeInMillis <= rangeEnd) {
                    val y = cursor.get(Calendar.YEAR)
                    val m = cursor.get(Calendar.MONTH)
                    val mid = Calendar.getInstance().apply {
                        clear(); set(y, m, 15)
                    }.timeInMillis
                    val monthEnd = Calendar.getInstance().apply {
                        clear(); set(y, m, 1); set(Calendar.DAY_OF_MONTH, getActualMaximum(Calendar.DAY_OF_MONTH))
                    }.timeInMillis
                    if (mid in rangeStart..rangeEnd) days.add(mid)
                    if (monthEnd in rangeStart..rangeEnd) days.add(monthEnd)
                    cursor.add(Calendar.MONTH, 1)
                }
            }
            PayFrequency.MONTHLY -> {
                val cursor = Calendar.getInstance().apply {
                    timeInMillis = rangeStart
                    set(Calendar.DAY_OF_MONTH, 1)
                }
                while (cursor.timeInMillis <= rangeEnd) {
                    val y = cursor.get(Calendar.YEAR)
                    val m = cursor.get(Calendar.MONTH)
                    val maxDay = cursor.getActualMaximum(Calendar.DAY_OF_MONTH)
                    val payday = Calendar.getInstance().apply {
                        clear(); set(y, m, minOf(maxDay, 15))
                    }.timeInMillis
                    if (payday in rangeStart..rangeEnd) days.add(payday)
                    cursor.add(Calendar.MONTH, 1)
                }
            }
            else -> {
                val stepDays = if (frequency == PayFrequency.WEEKLY) 7 else 14
                var payday = startOfDay(firstPaydayMillis)
                var i = 0
                while (i < 500 && payday <= rangeEnd) {
                    if (payday >= rangeStart) days.add(payday)
                    payday = addDays(payday, stepDays)
                    i++
                }
            }
        }
        return days.sorted()
    }

    fun scheduledPaychecksYtd(config: SalaryConfig, year: Int, asOf: Long = System.currentTimeMillis()): Int {
        val anchor = config.firstPaydayOfYearMillis
        val start = yearStart(year)
        val end = minOf(asOf, yearEnd(year))
        if (anchor == null) {
            val periods = config.payFrequency.periodsPerYear
            val elapsed = (end - start).toDouble() / (yearEnd(year) - start + 1)
            return (elapsed * periods).toInt().coerceAtLeast(1)
        }
        return countPaychecksInRange(anchor, config.payFrequency, start, end).coerceAtLeast(0)
    }

    fun scheduledPaychecksInYear(config: SalaryConfig, year: Int): Int {
        val counted = config.firstPaydayOfYearMillis
            ?.let { countPaychecksInRange(it, config.payFrequency, yearStart(year), yearEnd(year)) }
            ?: 0
        return if (counted > 0) counted else config.payFrequency.periodsPerYear
    }

    data class RemainingPaychecks(val future: Int, val unlogged: Int) {
        val total: Int get() = future + unlogged
    }

    /**
     * Paychecks still to be received in [year]: scheduled paydays after [asOf] plus
     * past paydays that were never logged (they still arrive, just not in the log).
     */
    fun remainingPaychecksForYear(
        config: SalaryConfig,
        year: Int,
        asOf: Long = System.currentTimeMillis()
    ): RemainingPaychecks {
        val anchor = if (canDetectMissingPaychecks(config, year)) {
            resolvePaydayAnchor(config, year, asOf)
        } else null
        if (anchor != null) {
            val from = maxOf(yearStart(year), addDays(startOfDay(asOf), 1))
            val future = if (from > yearEnd(year)) 0
            else enumeratePaydays(anchor, config.payFrequency, from, yearEnd(year)).size
            return RemainingPaychecks(future, missingPaydaysForYear(config, year, asOf).size)
        }
        val scheduledYtd = scheduledPaychecksYtd(config, year, asOf)
        return RemainingPaychecks(
            future = (scheduledPaychecksInYear(config, year) - scheduledYtd).coerceAtLeast(0),
            unlogged = (scheduledYtd - logsForYear(config, year).size).coerceAtLeast(0)
        )
    }

    private fun mergeLines(groups: List<List<PaycheckLineItem>>): List<YtdBreakdownLine> {
        val map = LinkedHashMap<String, YtdBreakdownLine>()
        for (group in groups) {
            for (item in group) {
                val label = item.label.ifBlank { "Other" }
                val existing = map[label]
                if (existing != null) {
                    map[label] = existing.copy(
                        amount = existing.amount + item.amount,
                        hours = existing.hours + (item.hours ?: 0.0)
                    )
                } else {
                    map[label] = YtdBreakdownLine(label, item.amount, item.hours ?: 0.0)
                }
            }
        }
        return map.values.filter { it.amount != 0.0 || it.hours != 0.0 }
    }

    private fun entryOvertimeHours(e: PaycheckLogEntry): Double {
        e.overtimeHours?.let { return it }
        val ot = e.earnings.firstOrNull { Regex("overtime|^ot\\b", RegexOption.IGNORE_CASE).containsMatchIn(it.label) }
        return ot?.hours ?: 0.0
    }

    private fun entryEarnings(e: PaycheckLogEntry): List<PaycheckLineItem> =
        if (e.earnings.isNotEmpty()) e.earnings
        else listOf(PaycheckLineItem(e.id, "Earnings", e.grossPay))

    private fun entryTaxes(e: PaycheckLogEntry): List<PaycheckLineItem> =
        if (e.taxes.isNotEmpty()) e.taxes
        else e.totalTaxes?.let { listOf(PaycheckLineItem(e.id, "Taxes", it)) } ?: emptyList()

    private fun entryPreTax(e: PaycheckLogEntry): List<PaycheckLineItem> =
        if (e.preTaxDeductions.isNotEmpty()) e.preTaxDeductions
        else e.totalPreTaxDeductions?.takeIf { it != 0.0 }
            ?.let { listOf(PaycheckLineItem(e.id, "Pre-tax deductions", it)) } ?: emptyList()

    private fun entryPostTax(e: PaycheckLogEntry): List<PaycheckLineItem> =
        if (e.postTaxDeductions.isNotEmpty()) e.postTaxDeductions
        else e.totalPostTaxDeductions?.takeIf { it != 0.0 }
            ?.let { listOf(PaycheckLineItem(e.id, "Post-tax deductions", it)) } ?: emptyList()

    private val OVERTIME_LABEL = Regex("overtime|^ot\\b", RegexOption.IGNORE_CASE)
    private val REGULAR_LABEL = Regex("regular|^reg\\b|base|salary|straight", RegexOption.IGNORE_CASE)

    /** Paystubs that best describe current withholding: newest real (not generated) stubs. */
    private const val RECENT_STUBS_FOR_RATES = 3

    private fun recentStubs(logs: List<PaycheckLogEntry>): List<PaycheckLogEntry> {
        val real = logs.filter { it.autoGenerated != true && it.grossPay > 0 }
        val pool = real.ifEmpty { logs.filter { it.grossPay > 0 } }
        return pool.takeLast(RECENT_STUBS_FOR_RATES)
    }

    /** Each label's share of gross across [stubs]; null when the stubs have no such lines. */
    private fun lineRates(
        stubs: List<PaycheckLogEntry>,
        lines: (PaycheckLogEntry) -> List<PaycheckLineItem>
    ): List<Pair<String, Double>>? {
        val gross = stubs.sumOf { it.grossPay }
        if (gross <= 0) return null
        val merged = mergeLines(stubs.map(lines))
        if (merged.isEmpty()) return null
        return merged.map { it.label to it.amount / gross }
    }

    /** Overtime ÷ regular hourly rate on the newest stub that itemizes both with hours. */
    private fun impliedOvertimeMultiplier(logs: List<PaycheckLogEntry>): Double? {
        for (entry in logs.asReversed()) {
            val ot = entry.earnings.firstOrNull {
                OVERTIME_LABEL.containsMatchIn(it.label) && (it.hours ?: 0.0) > 0
            } ?: continue
            val reg = entry.earnings.firstOrNull {
                !OVERTIME_LABEL.containsMatchIn(it.label) &&
                    REGULAR_LABEL.containsMatchIn(it.label) && (it.hours ?: 0.0) > 0
            } ?: continue
            if (reg.amount <= 0) continue
            val multiplier = (ot.amount / ot.hours!!) / (reg.amount / reg.hours!!)
            if (multiplier in 1.0..3.0) return multiplier
        }
        return null
    }

    /** Pay above straight time on overtime lines, the part the 2025–2028 deduction covers. */
    private fun overtimePremium(earnings: List<YtdBreakdownLine>, multiplier: Double): Double {
        val otPay = earnings.filter { OVERTIME_LABEL.containsMatchIn(it.label) }.sumOf { it.amount }
        if (otPay <= 0 || multiplier <= 1) return 0.0
        return otPay * (multiplier - 1) / multiplier
    }

    private fun scaleBreakdownLines(
        lines: List<YtdBreakdownLine>,
        factor: Double
    ): List<YtdBreakdownLine> =
        lines.map { line ->
            line.copy(
                amount = line.amount * factor,
                hours = line.hours * factor
            )
        }

    private fun extrapolationFromModel(
        modelAnnual: AnnualProjection,
        scheduledInYear: Int,
        overtimeMultiplier: Double
    ): AnnualExtrapolation {
        val perPaycheckGross =
            if (scheduledInYear > 0) modelAnnual.annualGrossPay / scheduledInYear else 0.0
        return AnnualExtrapolation(
            source = AnnualExtrapolation.Source.ESTIMATED,
            basedOnPaychecks = 0,
            scheduledPaychecksInYear = scheduledInYear,
            remainingPaychecksProjected = scheduledInYear,
            averageOvertimeHoursPerPaycheck = 0.0,
            projectOvertimeForward = true,
            overtimeMultiplier = overtimeMultiplier,
            annualGrossPay = modelAnnual.annualGrossPay,
            annualNetPay = modelAnnual.annualNetPay,
            annualTotalTaxes = modelAnnual.annualTotalTaxes,
            annualTotalDeductions =
                modelAnnual.annualPreTaxDeductions + modelAnnual.annualPostTaxDeductions,
            annualPreTaxDeductions = modelAnnual.annualPreTaxDeductions,
            annualPostTaxDeductions = modelAnnual.annualPostTaxDeductions,
            overtimeHours = modelAnnual.overtimeHoursUsed,
            perPaycheckNet = modelAnnual.perPaycheckNet,
            perPaycheckGross = perPaycheckGross,
            earnings = buildList {
                add(YtdBreakdownLine("Regular", modelAnnual.annualRegularPay))
                if (modelAnnual.annualOvertimePay > 0) {
                    add(
                        YtdBreakdownLine(
                            "Overtime",
                            modelAnnual.annualOvertimePay,
                            modelAnnual.overtimeHoursUsed
                        )
                    )
                }
            },
            taxes = buildList {
                add(YtdBreakdownLine("Federal income tax", modelAnnual.annualFederalTax))
                add(YtdBreakdownLine("State income tax", modelAnnual.annualStateTax))
                if (modelAnnual.annualCountyTax > 0) {
                    add(YtdBreakdownLine("County/local tax", modelAnnual.annualCountyTax))
                }
                add(YtdBreakdownLine("Social Security", modelAnnual.annualSocialSecurity))
                add(YtdBreakdownLine("Medicare", modelAnnual.annualMedicare))
            }.filter { it.amount != 0.0 },
            preTaxDeductions = modelAnnual.preTaxDeductionBreakdown.map {
                YtdBreakdownLine(it.name.ifBlank { "Pre-tax" }, it.amount)
            },
            postTaxDeductions = modelAnnual.postTaxDeductionBreakdown.map {
                YtdBreakdownLine(it.name.ifBlank { "Post-tax" }, it.amount)
            },
            employerContributions = emptyList(),
            effectiveTaxRate = modelAnnual.effectiveTaxRate
        )
    }

    private fun mergeBreakdownLineGroups(
        groups: List<List<YtdBreakdownLine>>
    ): List<YtdBreakdownLine> {
        val map = linkedMapOf<String, YtdBreakdownLine>()
        for (group in groups) {
            for (line in group) {
                val existing = map[line.label]
                if (existing != null) {
                    map[line.label] = existing.copy(
                        amount = existing.amount + line.amount,
                        hours = existing.hours + line.hours
                    )
                } else {
                    map[line.label] = line.copy()
                }
            }
        }
        return map.values.filter { it.amount != 0.0 || it.hours != 0.0 }
    }

    private fun scaleBreakdownForRemaining(
        lines: List<YtdBreakdownLine>,
        remaining: Int
    ): List<YtdBreakdownLine> =
        lines.map { line ->
            line.copy(
                amount = line.amount * remaining,
                hours = line.hours * remaining
            )
        }

    private data class ForwardBreakdown(
        val earnings: List<YtdBreakdownLine>,
        val taxes: List<YtdBreakdownLine>,
        val preTaxDeductions: List<YtdBreakdownLine>,
        val postTaxDeductions: List<YtdBreakdownLine>
    )

    private fun forwardBreakdownFromCalc(
        calc: PaycheckCalculation,
        overtimeHours: Double,
        config: SalaryConfig
    ): ForwardBreakdown {
        val earnings = buildList {
            add(YtdBreakdownLine("Regular", calc.regularPay))
            if (calc.overtimePay > 0) {
                add(YtdBreakdownLine("Overtime", calc.overtimePay, overtimeHours))
            }
        }
        val taxes = buildList {
            add(YtdBreakdownLine("Federal income tax", calc.federalTax))
            add(YtdBreakdownLine("State income tax", calc.stateTax))
            if (calc.countyTax > 0) {
                add(YtdBreakdownLine("County/local tax", calc.countyTax))
            }
            add(YtdBreakdownLine("Social Security", calc.socialSecurity))
            add(YtdBreakdownLine("Medicare", calc.medicare))
        }.filter { it.amount != 0.0 }
        return ForwardBreakdown(
            earnings = earnings,
            taxes = taxes,
            preTaxDeductions = calc.preTaxDeductionBreakdown.map {
                YtdBreakdownLine(it.name.ifBlank { "Pre-tax" }, it.amount)
            },
            postTaxDeductions = calc.postTaxDeductionBreakdown.map {
                YtdBreakdownLine(it.name.ifBlank { "Post-tax" }, it.amount)
            }
        )
    }

    /**
     * YTD actuals plus latest pay rate for remaining scheduled paychecks.
     * OT averages over logged paychecks and projects forward when enabled.
     */
    fun extrapolateAnnualFromLogs(
        config: SalaryConfig,
        calc: PaycheckCalculation,
        modelAnnual: AnnualProjection,
        year: Int,
        projectOvertimeForward: Boolean = true,
        asOf: Long = System.currentTimeMillis()
    ): AnnualExtrapolation {
        val scheduledInYear = scheduledPaychecksInYear(config, year)
        val logs = logsForYear(config, year).sortedBy { it.payDate }
        if (logs.isEmpty()) {
            return extrapolationFromModel(modelAnnual, scheduledInYear, config.overtimeMultiplier)
        }

        val remainingPaychecks = remainingPaychecksForYear(config, year, asOf)
        val remaining = remainingPaychecks.total
        val n = logs.size
        val latest = logs.last()
        val rate = effectiveRateAt(config, latest.payDate)
        val ytdNet = logs.sumOf { it.netPay }
        val ytdOTHours = logs.sumOf { entryOvertimeHours(it) }
        val avgOTPerPaycheck = if (n > 0) ytdOTHours / n else 0.0
        val forwardOT = if (projectOvertimeForward) avgOTPerPaycheck else 0.0
        val otMultiplier = impliedOvertimeMultiplier(logs) ?: config.overtimeMultiplier

        val forwardConfig = config.copy(
            payType = rate.payType,
            hourlyRate = rate.hourlyRate,
            annualSalary = rate.annualSalary,
            standardHoursPerPeriod = rate.standardHoursPerPeriod,
            overtimeHours = forwardOT,
            overtimeMultiplier = otMultiplier
        )
        val forwardPerPaycheck = PaycheckCalculator.calculate(
            forwardConfig,
            minOf(maxOf(asOf, latest.payDate), yearEnd(year))
        )
        val modelBreakdown = forwardBreakdownFromCalc(forwardPerPaycheck, forwardOT, config)
        val forwardGross = forwardPerPaycheck.grossPay

        val stubs = recentStubs(logs)
        val stubEarnings = stubs.flatMap { it.earnings }
        val overtimeLabel = stubEarnings.firstOrNull { OVERTIME_LABEL.containsMatchIn(it.label) }
            ?.label ?: "Overtime"
        val regularLabel = stubEarnings.firstOrNull {
            REGULAR_LABEL.containsMatchIn(it.label) && !OVERTIME_LABEL.containsMatchIn(it.label)
        }?.label ?: "Regular"
        fun fromStubs(
            lines: (PaycheckLogEntry) -> List<PaycheckLineItem>,
            fallback: List<YtdBreakdownLine>
        ): List<YtdBreakdownLine> =
            lineRates(stubs, lines)?.map { (label, rate) -> YtdBreakdownLine(label, rate * forwardGross) }
                ?: fallback

        val forwardEarnings = modelBreakdown.earnings.map {
            it.copy(label = if (it.label == "Overtime") overtimeLabel else regularLabel)
        }
        var forwardTaxes = scaleBreakdownForRemaining(fromStubs(::entryTaxes, modelBreakdown.taxes), remaining)
        val forwardPreTax =
            scaleBreakdownForRemaining(fromStubs(::entryPreTax, modelBreakdown.preTaxDeductions), remaining)
        val forwardPostTax =
            scaleBreakdownForRemaining(fromStubs(::entryPostTax, modelBreakdown.postTaxDeductions), remaining)

        val ytdTaxLines = mergeLines(logs.map { entryTaxes(it) })
        fun isSocialSecurity(line: YtdBreakdownLine) =
            classifyTaxLine(line.label) == TaxLineKind.SOCIAL_SECURITY
        val ssRate = config.taxOverrides.customSocialSecurityRate ?: FicaTaxRates.SOCIAL_SECURITY_RATE
        val socialSecurityRoom = (FederalTaxTables.socialSecurityWageBase(year) * ssRate -
            ytdTaxLines.filter(::isSocialSecurity).sumOf { it.amount }).coerceAtLeast(0.0)
        val forwardSocialSecurity = forwardTaxes.filter(::isSocialSecurity).sumOf { it.amount }
        if (forwardSocialSecurity > socialSecurityRoom) {
            val scale = socialSecurityRoom / forwardSocialSecurity
            forwardTaxes = forwardTaxes.map {
                if (isSocialSecurity(it)) it.copy(amount = it.amount * scale) else it
            }
        }

        val earnings = mergeBreakdownLineGroups(
            listOf(mergeLines(logs.map { entryEarnings(it) }), scaleBreakdownForRemaining(forwardEarnings, remaining))
        )
        val taxes = mergeBreakdownLineGroups(listOf(ytdTaxLines, forwardTaxes))
        val preTaxDeductions =
            mergeBreakdownLineGroups(listOf(mergeLines(logs.map { entryPreTax(it) }), forwardPreTax))
        val postTaxDeductions =
            mergeBreakdownLineGroups(listOf(mergeLines(logs.map { entryPostTax(it) }), forwardPostTax))

        val forwardGrossTotal = forwardGross * remaining
        val annualGrossPay = logs.sumOf { it.grossPay } + forwardGrossTotal
        val annualTotalTaxes = taxes.sumOf { it.amount }
        val annualPreTaxDeductions = preTaxDeductions.sumOf { it.amount }
        val annualPostTaxDeductions = postTaxDeductions.sumOf { it.amount }
        val annualNetPay = ytdNet + forwardGrossTotal -
            forwardTaxes.sumOf { it.amount } -
            forwardPreTax.sumOf { it.amount } -
            forwardPostTax.sumOf { it.amount }
        val paychecksInYear = n + remaining

        return AnnualExtrapolation(
            source = AnnualExtrapolation.Source.LOGGED,
            basedOnPaychecks = n,
            scheduledPaychecksInYear = scheduledInYear,
            remainingPaychecksProjected = remaining,
            unloggedPastPaychecks = remainingPaychecks.unlogged,
            averageOvertimeHoursPerPaycheck = avgOTPerPaycheck,
            projectOvertimeForward = projectOvertimeForward,
            overtimeMultiplier = otMultiplier,
            annualGrossPay = annualGrossPay,
            annualNetPay = annualNetPay,
            annualTotalTaxes = annualTotalTaxes,
            annualTotalDeductions = annualPreTaxDeductions + annualPostTaxDeductions,
            annualPreTaxDeductions = annualPreTaxDeductions,
            annualPostTaxDeductions = annualPostTaxDeductions,
            overtimeHours = ytdOTHours + forwardOT * remaining,
            perPaycheckNet = if (paychecksInYear > 0) annualNetPay / paychecksInYear else 0.0,
            perPaycheckGross = if (paychecksInYear > 0) annualGrossPay / paychecksInYear else 0.0,
            earnings = earnings,
            taxes = taxes,
            preTaxDeductions = preTaxDeductions,
            postTaxDeductions = postTaxDeductions,
            employerContributions = mergeLines(logs.map { it.employerContributions }),
            effectiveTaxRate =
                if (annualGrossPay > 0) annualTotalTaxes / annualGrossPay else calc.effectiveTaxRate
        )
    }

    fun summarize(
        config: SalaryConfig,
        calc: PaycheckCalculation,
        annual: AnnualProjection,
        year: Int,
        asOf: Long = System.currentTimeMillis(),
        projectOvertimeForward: Boolean = true
    ): YtdSummary {
        val logs = logsForYear(config, year)
        val scheduledYtd = scheduledPaychecksYtd(config, year, asOf)
        val scheduledInYear = scheduledPaychecksInYear(config, year)
        val remainingPaychecks = remainingPaychecksForYear(config, year, asOf)
        val remaining = if (logs.isNotEmpty()) remainingPaychecks.total else remainingPaychecks.future
        val annualExtrapolation = extrapolateAnnualFromLogs(
            config,
            calc,
            annual,
            year,
            projectOvertimeForward,
            asOf
        )
        val perPaycheckNet = annualExtrapolation.perPaycheckNet

        if (logs.isNotEmpty()) {
            val grossPay = logs.sumOf { it.grossPay }
            val netPay = logs.sumOf { it.netPay }
            val totalTaxes = logs.sumOf { it.totalTaxes ?: 0.0 }
            val totalPre = logs.sumOf { it.totalPreTaxDeductions ?: 0.0 }
            val totalPost = logs.sumOf { it.totalPostTaxDeductions ?: 0.0 }
            val overtimeHours = logs.sumOf { entryOvertimeHours(it) }
            val expectedNet = perPaycheckNet * logs.size
            val annualNetTarget = annualExtrapolation.annualNetPay
            return YtdSummary(
                year = year,
                source = YtdSummary.Source.LOGGED,
                paycheckCount = logs.size,
                scheduledPaychecksYtd = scheduledYtd,
                scheduledPaychecksInYear = scheduledInYear,
                grossPay = grossPay,
                netPay = netPay,
                totalTaxes = totalTaxes,
                totalPreTaxDeductions = totalPre,
                totalPostTaxDeductions = totalPost,
                overtimeHours = overtimeHours,
                earnings = mergeLines(logs.map { entryEarnings(it) }),
                taxes = mergeLines(logs.map { entryTaxes(it) }),
                preTaxDeductions = mergeLines(logs.map { entryPreTax(it) }),
                postTaxDeductions = mergeLines(logs.map { entryPostTax(it) }),
                employerContributions = mergeLines(logs.map { it.employerContributions }),
                annualExtrapolation = annualExtrapolation,
                annualNetTarget = annualNetTarget,
                progressPercent = if (annualNetTarget > 0) netPay / annualNetTarget * 100 else 0.0,
                remainingPaychecks = remaining,
                expectedNetToDate = expectedNet,
                netVariance = netPay - expectedNet,
                projectedAnnualTaxes = annualExtrapolation.annualTotalTaxes
            )
        }

        val n = scheduledYtd
        val earnings = buildList {
            add(YtdBreakdownLine("Regular", calc.regularPay * n))
            if (calc.overtimePay > 0) {
                add(YtdBreakdownLine("Overtime", calc.overtimePay * n, config.overtimeHours * n))
            }
        }
        val taxes = buildList {
            add(YtdBreakdownLine("Federal income tax", calc.federalTax * n))
            add(YtdBreakdownLine("State income tax", calc.stateTax * n))
            if (calc.countyTax > 0) {
                add(YtdBreakdownLine(if (config.county.isNotBlank()) "${config.county} tax" else "Local tax", calc.countyTax * n))
            }
            add(YtdBreakdownLine("Social Security", calc.socialSecurity * n))
            add(YtdBreakdownLine("Medicare", calc.medicare * n))
        }.filter { it.amount != 0.0 }
        return YtdSummary(
            year = year,
            source = YtdSummary.Source.ESTIMATED,
            paycheckCount = n,
            scheduledPaychecksYtd = scheduledYtd,
            scheduledPaychecksInYear = scheduledInYear,
            grossPay = calc.grossPay * n,
            netPay = calc.netPay * n,
            totalTaxes = calc.totalTaxes * n,
            totalPreTaxDeductions = calc.totalPreTaxDeductions * n,
            totalPostTaxDeductions = calc.totalPostTaxDeductions * n,
            overtimeHours = config.overtimeHours * n,
            earnings = earnings,
            taxes = taxes,
            preTaxDeductions = calc.preTaxDeductionBreakdown.map { YtdBreakdownLine(it.name.ifBlank { "Pre-tax" }, it.amount * n) },
            postTaxDeductions = calc.postTaxDeductionBreakdown.map { YtdBreakdownLine(it.name.ifBlank { "Post-tax" }, it.amount * n) },
            employerContributions = emptyList(),
            annualExtrapolation = annualExtrapolation,
            annualNetTarget = annualExtrapolation.annualNetPay,
            progressPercent = if (annualExtrapolation.annualNetPay > 0) {
                calc.netPay * n / annualExtrapolation.annualNetPay * 100
            } else 0.0,
            remainingPaychecks = remaining,
            expectedNetToDate = perPaycheckNet * n,
            netVariance = 0.0,
            projectedAnnualTaxes = annualExtrapolation.annualTotalTaxes
        )
    }

    fun logEntryFromCalculation(
        calc: PaycheckCalculation,
        payDate: Long,
        overtimeHours: Double?,
        notes: String? = null,
        autoGenerated: Boolean? = null
    ): PaycheckLogEntry {
        val lines = lineItemsFromCalculation(calc, overtimeHours)
        return PaycheckLogEntry(
            id = newId(),
            payDate = payDate,
            grossPay = calc.grossPay,
            netPay = calc.netPay,
            totalTaxes = calc.totalTaxes,
            totalPreTaxDeductions = calc.totalPreTaxDeductions,
            totalPostTaxDeductions = calc.totalPostTaxDeductions,
            overtimeHours = overtimeHours,
            notes = notes,
            earnings = lines.earnings,
            taxes = lines.taxes,
            preTaxDeductions = lines.preTaxDeductions,
            postTaxDeductions = lines.postTaxDeductions,
            autoGenerated = autoGenerated
        )
    }

    /** Build estimated log entries for scheduled paydates in [year] that are not yet logged. */
    fun generatePaycheckLogsForMissingDates(
        config: SalaryConfig,
        year: Int,
        asOf: Long = System.currentTimeMillis()
    ): List<PaycheckLogEntry> =
        missingPaydaysForYear(config, year, asOf).map { payDate ->
            val calc = PaycheckCalculator.calculate(config, payDate)
            logEntryFromCalculation(
                calc,
                payDate,
                config.overtimeHours,
                autoGenerated = true
            )
        }

    /** Build itemized lines from a calculation (used for "prefill from calculator"). */
    fun lineItemsFromCalculation(calc: PaycheckCalculation, overtimeHours: Double?): LogLines {
        val earnings = buildList {
            add(PaycheckLineItem(newId(), "Regular", calc.regularPay))
            if (calc.overtimePay > 0) {
                add(PaycheckLineItem(newId(), "Overtime", calc.overtimePay, overtimeHours))
            }
        }
        val taxes = buildList {
            add(PaycheckLineItem(newId(), "Federal income tax", calc.federalTax))
            add(PaycheckLineItem(newId(), "State income tax", calc.stateTax))
            add(PaycheckLineItem(newId(), "Social Security", calc.socialSecurity))
            add(PaycheckLineItem(newId(), "Medicare", calc.medicare))
            if (calc.countyTax > 0) add(PaycheckLineItem(newId(), "Local tax", calc.countyTax))
        }
        return LogLines(
            earnings = earnings,
            taxes = taxes,
            preTaxDeductions = calc.preTaxDeductionBreakdown.map { PaycheckLineItem(newId(), it.name, it.amount) },
            postTaxDeductions = calc.postTaxDeductionBreakdown.map { PaycheckLineItem(newId(), it.name, it.amount) }
        )
    }

    data class LogLines(
        val earnings: List<PaycheckLineItem>,
        val taxes: List<PaycheckLineItem>,
        val preTaxDeductions: List<PaycheckLineItem>,
        val postTaxDeductions: List<PaycheckLineItem>
    )

    val earningsCategories = listOf(
        "Regular", "Overtime", "Bonus", "Commission", "Holiday", "PTO", "Tips", "Reimbursement", "Other"
    )

    const val INFERRED_RAISE_ID_PREFIX = "inferred-"

    data class InferredStartingPay(
        val effectiveDate: Long,
        val regularGrossPerPaycheck: Double,
        val payType: PayType,
        val hourlyRate: Double,
        val annualSalary: Double,
        val standardHoursPerPeriod: Double
    )

    data class InferredPayRateRaise(
        val change: PayRateChange,
        val percentIncrease: Double,
        val perPaycheckIncrease: Double,
        val previousRegularGross: Double,
        val newRegularGross: Double
    )

    data class InferredPayRates(
        val startingRate: InferredStartingPay?,
        val raises: List<InferredPayRateRaise>
    )

    private data class ParsedRegularPay(
        val regularGross: Double,
        val standardHours: Double
    )

    private fun regularGrossFromLog(
        entry: PaycheckLogEntry,
        config: SalaryConfig
    ): ParsedRegularPay? {
        if (entry.grossPay <= 0.0) return null

        var regularGross = entry.grossPay
        var standardHours = config.standardHoursPerPeriod

        if (entry.earnings.isNotEmpty()) {
            val regular = entry.earnings.find { it.label.trim().matches(Regex("(?i)^regular.*")) }
            val overtime = entry.earnings.find {
                it.label.trim().matches(Regex("(?i)(overtime|^ot\\b).*"))
            }
            if (regular != null) {
                regularGross = regular.amount
                if ((regular.hours ?: 0.0) > 0.0) standardHours = regular.hours!!
            } else if (overtime != null) {
                regularGross = (entry.grossPay - overtime.amount).coerceAtLeast(0.0)
            }
        } else if ((entry.overtimeHours ?: 0.0) > 0.0) {
            val rate = effectiveRateAt(config, entry.payDate)
            val overtimePay = rate.hourlyRate * config.overtimeMultiplier * entry.overtimeHours!!
            regularGross = (entry.grossPay - overtimePay).coerceAtLeast(0.0)
        }

        if (regularGross <= 0.0) return null
        return ParsedRegularPay(regularGross, standardHours)
    }

    private fun impliedRateFromRegularGross(
        regularGross: Double,
        payType: PayType,
        frequency: PayFrequency,
        standardHours: Double
    ): Pair<Double, Double> {
        return if (payType == PayType.SALARY) {
            0.0 to regularGross * frequency.periodsPerYear
        } else {
            (if (standardHours > 0.0) regularGross / standardHours else 0.0) to 0.0
        }
    }

    fun inferPayRatesFromLogs(config: SalaryConfig, year: Int): InferredPayRates {
        val logs = logsForYear(config, year).sortedBy { it.payDate }
        if (logs.isEmpty()) return InferredPayRates(null, emptyList())

        var previousRegular: Double? = null
        var startingRate: InferredStartingPay? = null
        val raises = mutableListOf<InferredPayRateRaise>()

        for (log in logs) {
            val parsed = regularGrossFromLog(log, config) ?: continue
            val (hourlyRate, annualSalary) = impliedRateFromRegularGross(
                parsed.regularGross,
                config.payType,
                config.payFrequency,
                parsed.standardHours
            )

            if (previousRegular == null) {
                startingRate = InferredStartingPay(
                    effectiveDate = log.payDate,
                    regularGrossPerPaycheck = parsed.regularGross,
                    payType = config.payType,
                    hourlyRate = hourlyRate,
                    annualSalary = annualSalary,
                    standardHoursPerPeriod = parsed.standardHours
                )
                previousRegular = parsed.regularGross
                continue
            }

            if (parsed.regularGross > previousRegular + 0.01) {
                val perPaycheckIncrease = parsed.regularGross - previousRegular
                val percentIncrease =
                    if (previousRegular > 0.0) perPaycheckIncrease / previousRegular * 100.0 else 0.0
                val change = PayRateChange(
                    id = "$INFERRED_RAISE_ID_PREFIX${log.payDate}",
                    effectiveDate = log.payDate,
                    payType = config.payType,
                    hourlyRate = hourlyRate,
                    annualSalary = annualSalary,
                    standardHoursPerPeriod = parsed.standardHours,
                    note = "+${"%.1f".format(percentIncrease)}% (+${
                        "%.2f".format(perPaycheckIncrease)
                    }/paycheck)"
                )
                raises.add(
                    InferredPayRateRaise(
                        change = change,
                        percentIncrease = percentIncrease,
                        perPaycheckIncrease = perPaycheckIncrease,
                        previousRegularGross = previousRegular,
                        newRegularGross = parsed.regularGross
                    )
                )
                previousRegular = parsed.regularGross
            }
        }

        return InferredPayRates(startingRate, raises)
    }

    fun applyInferredPayRatesToConfig(config: SalaryConfig, year: Int): SalaryConfig {
        val yearLogs = logsForYear(config, year)
        val manualRaises = config.payRateHistory.filter {
            !it.id.startsWith(INFERRED_RAISE_ID_PREFIX)
        }
        val otherInferred = config.payRateHistory.filter {
            it.id.startsWith(INFERRED_RAISE_ID_PREFIX) && yearOf(it.effectiveDate) != year
        }

        if (yearLogs.isEmpty()) {
            val cleaned = manualRaises + otherInferred
            return if (cleaned.size == config.payRateHistory.size) config
            else config.copy(payRateHistory = cleaned)
        }

        val inferred = inferPayRatesFromLogs(config, year)
        var next = config.copy(
            payRateHistory = manualRaises + otherInferred + inferred.raises.map { it.change }
        )
        inferred.startingRate?.let { start ->
            next = next.copy(
                payType = start.payType,
                hourlyRate = start.hourlyRate,
                annualSalary = start.annualSalary,
                standardHoursPerPeriod = start.standardHoursPerPeriod
            )
        }
        return next
    }

    fun applyInferredPayRatesForAllLogYears(config: SalaryConfig): SalaryConfig {
        val logYears = config.paycheckLog.map { yearOf(it.payDate) }.distinct()
        val inferredYears = config.payRateHistory
            .filter { it.id.startsWith(INFERRED_RAISE_ID_PREFIX) }
            .map { yearOf(it.effectiveDate) }
        var next = config
        for (year in (logYears + inferredYears).distinct()) {
            next = applyInferredPayRatesToConfig(next, year)
        }
        return next
    }
}
